### ISSUE TITLE
write_to_png fails with IOBuffer on julia 0.4

### ISSUE THREAD

**Issue by dcjones** [JuliaGraphics/Cairo.jl#100]
Not sure if this is a Julia or Cairo.jl issue. The following works on Julia 0.3, but not 0.4.

```julia
using Cairo

surf = CairoARGBSurface(100, 100)
out = IOBuffer()
write_to_png(surf, out)
```

On 0.4, I get
```
ERROR: LoadError: ArgumentError: write failed, IOBuffer is not writeable
```

The reason seems to be that the IOBuffer that is supposed to be passed to `write_to_stream_callback`, somehow ends up as random garbage. If you show it, you'll get something like
```julia
IOBuffer(data=UInt8[...], readable=false, writable=false, seekable=false, append=false, size=140382156285440, maxsize=140382181623072, ptr=140734615164048, mark=13339137704)
```

**Comment by timholy** [comment]
Works for me now, closing.
