### ISSUE TITLE
Build provider code for openSUSE zypper?

### ISSUE THREAD

**Issue by colbec** [JuliaGraphics/Cairo.jl#128]
On openSUSE Leap 42.1, which uses rpm based Zypper package manager, Julia requests "using PyPlot" result in a curious but harmless bug which forces the Yast window to pop up requesting root access. Denial at this window allows the process to continue and PyPlot appears to work ok.
It is hard to find out where this call is coming from. In an effort to straighten things out some provider code for Zypper has been added to BinDeps (https://github.com/JuliaLang/BinDeps.jl/issues/188).
Since Cairo in the deps code has some provision for providers, now that BinDeps allows calls to zypper, is the Cairo community willing to entertain changes to the build dependencies which may use this provider rather than force a build from source?

**Comment by tkelman** [comment]
Makes sense to me. This package is sort of community-maintained at the moment.

Would have to tag a version of BinDeps that includes Cairo support first, then change the BinDeps version requirement in `REQUIRE` accordingly. For now you can try local testing with `Pkg.checkout("BinDeps")` to see if you can get the right `deps/build.jl` setup.

**Comment by nalimilan** [comment]
@tkelman You mean "a version of BinDeps that includes zypper support", right?

**Comment by tkelman** [comment]
Yes, thank you.

**Comment by colbec** [comment]
Well, I guess my proposed changes in #129 were not welcomed by the Travis tester. I will look at the output, but feedback would be nice :)

**Comment by timholy** [comment]
Fixed in #129.
