### ISSUE TITLE
More extensive tests

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/Cairo.jl#140]
One "easy" way to do this would be to check against the output of the `samples` directory. However, other packages have revealed that different lib versions of Cairo produce slightly different output, so one would have to do "fuzzy" comparison, e.g., using Images.jl.

**Comment by lobingera** [comment]
I remember looking into making pdiff which is used in libcairo regression itself but that was superceeded by your work on visual comparison in Images (i guess). 
btw: samples are not a good regression as the date and time are stamped into the first line...

**Comment by lobingera** [comment]
Actually only running all the samples was already helpful in finding the memory problems and a test suite that runs all commands might be a first goal. For testing the painting operators i think something like drawing space filling curves like hilbert might get us easy testing. If you paint this

![a](https://cloud.githubusercontent.com/assets/5199059/18962058/87ca09f8-866f-11e6-81ee-b9170330de25.png)

with a linewidth of 8 (above picture 2):

![a](https://cloud.githubusercontent.com/assets/5199059/18962096/b6814356-866f-11e6-93c4-2cefcb05b0fd.png)

... and checking if all pixels are exactly the same color might not be complicated.

**Comment by timholy** [comment]
I also just turned on Coveralls (we've been submitting results but I guess they weren't being accepted).

**Comment by lobingera** [comment]
86% isn't great, but ...

**Comment by timholy** [comment]
Quite fantastic, actually!
