### ISSUE TITLE
OSX julia-0.5 segfault on sample_imagepattern

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/Cairo.jl#146]
I can't reproduce this on linux, so I can't fix it, but see e.g., https://travis-ci.org/JuliaGraphics/Cairo.jl/builds/139925587, and click on the OSX nightly run. It may not be 100% reliable, but it's shown up on the majority of recent travis builds.

**Comment by lobingera** [comment]
just for more context, message copied from travis log
```
julia(6265,0x7fff77df3310) malloc: *** error for object 0x7fe54d281f60: pointer being freed was not allocated

*** set a breakpoint in malloc_error_break to debug

signal (6): Abort trap: 6

while loading /Users/travis/.julia/v0.5/Cairo/samples/sample_imagepattern.jl, in expression starting on line 29

__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)

Allocations: 3596950 (Pool: 3595463; Big: 1487); GC: 5
```
@timholy Do you have experience to track down, what instance is messaging what here? (it's julia itself, seeing a memory error?)
and btw: https://travis-ci.org/JuliaGraphics/Cairo.jl/builds/139835595 passed

**Comment by lobingera** [comment]
i tried to recreate with a dummy package running only sample_imagepattern and running Pkg.test() on my Cairo.jl fork.

https://travis-ci.org/lobingera/L1Dummy/builds/140205864
https://travis-ci.org/JuliaGraphics/Cairo.jl/builds/140209942
Both passes.

**Comment by tkelman** [comment]
saw a "double free or corruption" on pkgeval (ubuntu 14.04, 64 bit) at this same place here: https://github.com/JuliaLang/julia/pull/18276#issuecomment-245477100

**Comment by lobingera** [comment]
I mentioned this in my comment https://github.com/JuliaLang/julia/pull/18276#issuecomment-244896049 and https://github.com/JuliaGraphics/Cairo.jl/pull/155#issuecomment-242906598.

The error "double free or corruption" first only showed up on travis and only on linux, later i could see it with my local linux install also. The point when it's happening seemed to be triggered by GC when julia calls destroy on elements allocated by libcairo.
