### ISSUE TITLE
Pkg.build("Cairo") Issue

### ISSUE THREAD

**Issue by jebej** [JuliaGraphics/Cairo.jl#147]
Hello, on Julia 0.4.6 and Windows 10 64bit I get:

``` julia
julia> Pkg.build("Cairo")
INFO: Building WinRPM
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building Cairo

PowerShell[.exe] [-PSConsoleFile <file> | -Version <version>]
    [-NoLogo] [-NoExit] [-Sta] [-Mta] [-NoProfile] [-NonInteractive]
    [-InputFormat {Text | XML}] [-OutputFormat {Text | XML}]
    [-WindowStyle <style>] [-EncodedCommand <Base64EncodedCommand>]
    [-File <filePath> <args>] [-ExecutionPolicy <ExecutionPolicy>]
    [-Command { - | <script-block> [-args <arg-array>]
                  | <string> [<CommandParameters>] } ]

PowerShell[.exe] -Help | -? | /?
...
```

It seems the Powershell command is called with invalid arguments.

Note that Cairo still seems to work (tried with an example).

**Comment by tkelman** [comment]
What happens if you run ``` run(`powershell -Command "(new-object net.webclient).DownloadFile(\"https://google.com\", \"google.html\")"`) ``` ?

**Comment by jebej** [comment]
It works, the page downloads.

**Comment by tkelman** [comment]
How about ``` run(`powershell -help`) ``` or ``` run(`powershell -NoProfile -Command ""`) ``` ?

**Comment by jebej** [comment]
With the first command the help appears, that's actually the same message as above. Is it possible that Cairo is calling that commend?

Nothing happens with the second command.

**Comment by tkelman** [comment]
Oh, I think the message is actually harmless, we just need to tag BinDeps to suppress it.
