### ISSUE TITLE
Build fails on Debian 8.2

### ISSUE THREAD

**Issue by dolejm1** [JuliaGraphics/Cairo.jl#152]
Pkg.build("Cairo") ends with:

INFO: Building Cairo
signal (11): Segmentation fault
unknown function (ip: 0x7f0000344d3b)
ERROR: Build process failed.
 in build! at pkg/entry.jl:701
 in build at pkg/entry.jl:720
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in build at pkg.jl:64
--------------------------------------------------------------------------------
And
BinDeps.debug("Cairo") ends with:

INFO: Reading build script...
The package declares 1 dependencies.
 - Library Group "cairo"
signal (11): Segmentation fault
unknown function (ip: 0x7fe01961bd3b)
Segmentation fault

**Comment by lobingera** [comment]
julia version?

**Comment by dolejm1** [comment]
4.6

**Comment by dolejm1** [comment]
It looks like a problem on my side.
I decided to reinstall everything, and Cairo builds.
