### ISSUE TITLE
Can Cairo.jl create transparent PNGs?

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Cairo.jl#158]
I wasn't able to find out whether raw Cairo can create PNG files with transparent backgrounds, but — if it can — can Cairo.jl do it as well?  

Transparent backgrounds usually look like chessboards when you open them in an editor:

![screen shot 2016-09-14 at 12 38 51](https://cloud.githubusercontent.com/assets/52289/18510867/44811df6-7a78-11e6-85b7-c956abf45685.png)

**Comment by lobingera** [comment]
yes, i changed the sample_fill_and_stroke2 example at two places:
* using a surface that can utilize transparency
* filling the background with a 0% opaque color (i choose transparent black)

```
## header to provide surface and context
using Cairo
c = CairoARGBSurface(256,256);
cr = CairoContext(c);

save(cr);
set_source_rgba(cr,0.0,0.0,0.0,0.0); # transparent black
rectangle(cr,0.0,0.0,256.0,256.0); # background
fill(cr);
restore(cr);

save(cr);
## original example, following here
move_to(cr, 128.0, 25.6);
line_to(cr, 230.4, 230.4);
rel_line_to(cr, -102.4, 0.0);
curve_to(cr, 51.2, 230.4, 51.2, 128.0, 128.0, 128.0);
close_path(cr);

move_to(cr, 64.0, 25.6);
rel_line_to(cr, 51.2, 51.2);
rel_line_to(cr, -51.2, 51.2);
rel_line_to(cr, -51.2, -51.2);
close_path(cr);

set_line_width(cr, 10.0);
set_source_rgb(cr, 0, 0, 1);
fill_preserve(cr);
set_source_rgb(cr, 0, 0, 0);
stroke(cr);

## mark picture with current date
restore(cr);
move_to(cr,0.0,12.0);
set_source_rgb(cr, 0,0,0);
show_text(cr,Libc.strftime(time()));
write_to_png(c,"sample_fill_and_stroke3.png");
```

and this gives me in a display the following picture:
![snapshot7](https://cloud.githubusercontent.com/assets/5199059/18521566/db6cbdfe-7aac-11e6-8ad5-bf871235273a.png)

**Comment by cormullion** [comment]
OK, thanks!
