### ISSUE TITLE
Cairo.jl's text interface

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Cairo.jl#161]
I'm puzzled by the text handling in Cairo.jl, and seek enlightenment... Apparently Cairo offers a "toy" version, and a "serious" version of text setting. Cairo.jl seems to offer some of both approaches, but I can't work out how to use the "serious" version with Pango (which is mentioned (`ccall((:pango_font_description_from_string`) so is presumably supported). 

For example, I can set the font and font size only with the "toy" version:

```
using Cairo

c = Cairo.CairoPDFSurface("/tmp/cairo-text.pdf", 1200, 1200)
cr = CairoContext()

set_source_rgb(cr, 1, 1, 1)       # white
rectangle(cr, 0.0, 0.0, 800, 800) # background
fill(cr)

translate(cr, 400, 400)

# This is the "pro" text interface:
set_source_rgb(cr, 1.0, 0.5, 0.5)  #
set_font_size(cr, 90.0)
set_font_face(cr, "Times-Italic")
text(cr, 0, 0, "Hello World", halign="left", valign="top", angle=0, markup=false)

# and this is the "toy" text interface
translate(cr, 0, 40)
set_source_rgb(cr, 0.5, 0.5, 1.0)
select_font_face(cr, "Times-Italic", Cairo.FONT_SLANT_NORMAL, Cairo.FONT_WEIGHT_BOLD)
show_text(cr, "Hello again")

Cairo.finish()
```
![screen shot 2016-09-22 at 16 38 02](https://cloud.githubusercontent.com/assets/52289/18755162/f8bb2bf2-80e2-11e6-820f-cb5fc4a953e6.png)

I expected the "toy" version to fail, but it's the "serious" version which doesn't find the font or respect the size change. How do I specify typesetting without using the "toy" version? I expect it's something simple...

**Comment by lobingera** [comment]
See some examples in #138

**Comment by cormullion** [comment]
Hi Andreas - thanks for some clues. I think the first thing I noticed is that there are two ways of specifying fonts. `set_font_face()` ("serious") uses a font description string with the style and size information built in. This might be so as to link with `.julia/v0.5/Homebrew/deps/usr/var/homebrew/linked/fontconfig` which is installed with Cairo and might be used for finding fonts. But `select_font_face()` ("toy") seems to prefer the PostScript name of the font, no spaces, rather hyphens:

So either:

```
set_font_face(cr, "Agenda Black 72")
text(cr, 0, 0, "Hello World", halign="left", valign="top", angle=0, markup=false)

set_font_size(cr, 72)
select_font_face(cr, "Agenda-Black", Cairo.FONT_SLANT_NORMAL, Cairo.FONT_WEIGHT_BOLD)
```

![screen shot 2016-09-23 at 10 08 58](https://cloud.githubusercontent.com/assets/52289/18780499/c96a4048-8175-11e6-89a6-084f18cd3768.png)

work, giving different sizes though: the "toy" interface is the correct size (72 points), the "serious" interface is too large (it's 96 points.)

(Strangely Agenda Black doesn't appear in the fontconfig list; I assume it's detected because it's a font that's been activated by font management software.

I'm working on macOS, perhaps things are just as unpredictable on here as they are on Windows...

And since this is moving outside the realm of Julia and Cairo.jl, I'll close this for now.
