### ISSUE TITLE
_jl_libcairo not defined

### ISSUE THREAD

**Issue by madeleineudell** [JuliaGraphics/Cairo.jl#165]
This error is getting old, but here it is again: I upgraded my Mac to the new OSX Sierra, and I am now seeing the error

_jl_libcairo not defined

with IJulia on Julia v0.5. 

Specifically, the following command works at the Julia prompt but produces the error `_jl_libcairo not defined` in IJulia:
```
using Cairo, Gadfly
plot(x=rand(4), y=rand(4), Geom.point)
```
Is there a recommended fix?

**Comment by StefanKarpinski** [comment]
When I had this problem, it was due to confusion between two different installs of anaconda. I deleted the user-space one, leaving only the Conda.jl one and that fixed the issue. Not a general solution, but it worked.

**Comment by kmsquire** [comment]
I just ran into this and followed the trail of breadcrumbs, first to the workaround at https://github.com/JuliaGraphics/Cairo.jl/issues/124#issuecomment-170611741, then here.

From the linked issue, this is probably a `BinDeps` problem (or at least should be addressed there).

**Comment by kmsquire** [comment]
I think the report by @staticfloat at https://github.com/JuliaLang/BinDeps.jl/issues/251 is attempting to address this issue.

**Comment by staticfloat** [comment]
Indeed.  The workaround, until we fix BinDeps is to just manually install both `cairo` and `pango` through Homebrew, e.g. `using Homebrew; Homebrew.add("cairo"); Homebrew.add("pango")`

**Comment by montyvesselinov** [comment]
`using Homebrew; Homebrew.add("cairo"); Homebrew.add("pango")` does not help:

```
NFO: Precompiling module NMFk.
ERROR: LoadError: UndefVarError: _jl_libcairo not defined
Stacktrace:
 [1] anonymous at ./<missing>:?
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
```

**Comment by montyvesselinov** [comment]
```
using Homebrew
Homebrew.brew(`reinstall fontconfig`)
Pkg.build("Cairo")
using Cairo # works
```
fixes thos

**Comment by StefanKarpinski** [comment]
I'm pretty sure there's nothing here that's actionable for Base Julia at this point...

**Comment by montyvesselinov** [comment]
I agree. It is a just an issue when homebrew is broken and needs to be fixed.
