### ISSUE TITLE
Array deprecations for Julia v0.6?

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Cairo.jl#170]
If I understand correctly, these lines in Cairo.jl produce deprecation warnings in Julia v0.6+:

    654    points = Array(Float64,(element_length-1)*2)
    907    w = Array(Int32,2)
    923    text_extents(ctx::CairoContext,value::AbstractString) = text_extents!(ctx,value,Array(Float64, 6, 1))

and should be modified to:

    654    points = Array{Float64}((element_length-1)*2)
    907    w = Array{Int32}(2)
    923    text_extents(ctx::CairoContext,value::AbstractString) = text_extents!(ctx,value,Array{Float64}(6, 1))

Is it better to handle these with a `Compat`-expression or, since the modified versions appear to work OK with Julia v0.4 and v0.5, should they just be modified?

**Comment by tkelman** [comment]
just change them. though if the number of dimensions is known statically (only one or two input), it's arguably more explicit to use `Vector{T}(n)` or `Matrix{T}(m,n)`

**Comment by cormullion** [comment]
Hopefully now fixed by #171.
