### ISSUE TITLE
v0.6 deprecated syntax inner constructor

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Cairo.jl#172]
i got here 3:

WARNING: deprecated syntax "inner constructor CairoSurface(...) around /home/lobi/.julia/v0.6/Cairo/src/Cairo.jl:114".
Use "CairoSurface{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor CairoSurface(...) around /home/lobi/.julia/v0.6/Cairo/src/Cairo.jl:119".
Use "CairoSurface{T}(...) where T" instead.

WARNING: deprecated syntax "inner constructor CairoSurface(...) around /home/lobi/.julia/v0.6/Cairo/src/Cairo.jl:124".
Use "CairoSurface{T}(...) where T" instead.

**Comment by ararslan** [comment]
Fixed by #182

**Comment by lobingera** [comment]
agreed
