### ISSUE TITLE
v0.6 LoadError ...  ccall: argument type Ref should have an element type, not Ref{T}

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Cairo.jl#173]
run sample_imagestream.jl

  LoadError: error compiling read_from_png: ccall: argument type Ref should have an element type, not Ref{T}
  Stacktrace:
   [1] include_from_node1(::String) at ./loading.jl:539
   [2] include(::String) at ./sysimg.jl:14
   [3] macro expansion at /home/lobi/.julia/v0.6/Cairo/test/runtests.jl:80 [inlined]
   [4] macro expansion at ./test.jl:853 [inlined]
   [5] anonymous at ./<missing>:?
   [6] include_from_node1(::String) at ./loading.jl:539
   [7] include(::String) at ./sysimg.jl:14
   [8] process_options(::Base.JLOptions) at ./client.jl:305
   [9] _start() at ./client.jl:371
  while loading /home/lobi/.julia/v0.6/Cairo/samples/sample_imagestream.jl, in expression starting on line 20

**Comment by tkelman** [comment]
is it a ref to a ref?

**Comment by lobingera** [comment]
i don't think so:
```
function read_from_stream_callback(s::IO, buf::Ptr{UInt8}, len::UInt32)
    # wrap the provided buf into a julia Array
    b1 = unsafe_wrap(Array,buf,len)
    
    # read from stream
    nb = readbytes!(s,b1,len)

    # provide a return status
    (nb == len) ? STATUS_SUCCESS : STATUS_READ_ERROR
end
...
get_readstream_callback(T) = cfunction(read_from_stream_callback, Int32, (Ref{T}, Ptr{UInt8}, UInt32))
...
function read_from_png{T<:IO}(stream::T)
    callback = get_readstream_callback(T)
    ptr = ccall((:cairo_image_surface_create_from_png_stream, Cairo._jl_libcairo),
                Ptr{Void}, (Ptr{Void},Ref{T}), callback, stream)
    w = ccall((:cairo_image_surface_get_width,Cairo._jl_libcairo),
              Int32, (Ptr{Void},), ptr)
    h = ccall((:cairo_image_surface_get_height,Cairo._jl_libcairo),
              Int32, (Ptr{Void},), ptr)
    Cairo.CairoSurface(ptr, w, h)
end

```

and read_from_png is called with IObuffer as input.

**Comment by tkelman** [comment]
what is the C type equivalent to a ref of a Julia IObuffer supposed to be?

**Comment by lobingera** [comment]
```
cairo_surface_t *
cairo_image_surface_create_from_png_stream
                               (cairo_read_func_t read_func,
                                void *closure);
```

**Comment by lobingera** [comment]
I seem to have a working solution with 

function read_from_png{T<:IO}(stream::T)
    callback = get_readstream_callback(T)
    ptr = ccall((:cairo_image_surface_create_from_png_stream, Cairo._jl_libcairo),
                Ptr{Void}, (Ptr{Void},Ref{IO}), callback, stream)

@tkelman Do you agree?

**Comment by tkelman** [comment]
not sure, but if it works?

**Comment by lobingera** [comment]
I always thought, you were the computer scientist and i'm the engineer...

**Comment by tkelman** [comment]
nope, my degrees are all in mechanical engineering
