### ISSUE TITLE
Mesh patterns

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Cairo.jl#174]
Does Cairo.jl support [mesh patterns](https://cairographics.org/manual/cairo-cairo-pattern-t.html#cairo-pattern-create-mesh)? (It was added to Cairo version 1.12 in 2012). 

Are there technical barriers, or is it just waiting for someone to do it?

**Comment by lobingera** [comment]
I put some work into https://github.com/JuliaGraphics/Cairo.jl/pull/83, but it never got merged.

**Comment by cormullion** [comment]
Cool, you've already done all the hard work! Was there a problem with it, and can you re-open it?

**Comment by tknopp** [comment]
@lobingera I think best in that situation is to ping some people. This is typical for a package that has not a defined maintainer. If you want to get commit access just ask @timholy or @tkelman.

**Comment by lobingera** [comment]
@cormullion, i recognized, that getting cairo 1.12 might be an issue on some platforms. And other other things that were not clear, like how to deal with versioning of libraries and packages anyway.

@tknopp, there wasn't a situation. And i think the package has maintainers: the JuliaGraphics group.

**Comment by timholy** [comment]
@lobingera, I'm pretty sure I gave you commit access some time ago? Does it not work?

**Comment by timholy** [comment]
You indeed seem to be listed as having the requisite authority to merge pull requests. It's why I kept saying stuff like "merge whenever you're ready" and didn't merge on your behalf.

If this isn't working for you, then accept my apologies for any confusion. And we should rectify this ASAP.

**Comment by tknopp** [comment]
:-) If the package maintainer is "the JuliaGraphics group" it has effectively not an active maintainer.

**Comment by timholy** [comment]
Nonsense, @lobingera is the maintainer :smile:. I maintain some other packages in JuliaGraphics (like the whole colors suite), but I can't do them all and I'm grateful for y'all's help.

**Comment by tknopp** [comment]
Yes I think what we need here is clear communication

**Comment by tknopp** [comment]
And if a ship is sailing without a captain we should find some standard text in README.md that should indicate this

**Comment by lobingera** [comment]
@timholy, i wasn't aware (but it's good news) and actually how can i check this without comitting?

**Comment by tkelman** [comment]
Could try to create a temporary branch - click the "master" dropdown on https://github.com/JuliaGraphics/Cairo.jl, start typing a new branch name, if it lets you create it you're good and should be able to commit things too.

**Comment by tknopp** [comment]
go to any open PR and check if there is a button that lets you commit

**Comment by tknopp** [comment]
just try to commit #167 which is your PR. You should be able to press the "merge" button

**Comment by timholy** [comment]
> Yes I think what we need here is clear communication

I'll add your name to the Gtk README as the official maintainer, OK? :smile:

**Comment by tknopp** [comment]
Hey no. I have not even commit access ;-)

**Comment by tknopp** [comment]
Proposal: "This package has currently no fully active maintainer. You are encouraged to send a bug report but you cannot expect that it will be directly solved. If you want to improve the package yourself, please make a PR and ping ???"

This would require some sort of "shadow maintainer" that can then give the people commit rights

**Comment by cormullion** [comment]
Or make a new release?

**Comment by tknopp** [comment]
This is best solved by someone with admin rights to install attobot

**Comment by timholy** [comment]
> Hey no. I have not even commit access ;-)

Yes you do---you even have admin rights, so you can modify the settings yourself. (Note I was talking about Gtk.jl, not Cairo.jl or the C-language Gtk project.)

> This package has currently no fully active maintainer. You are encouraged to send a bug report but you cannot expect that it will be directly solved. If you want to improve the package yourself, please make a PR and ping ???"

That would be fine, but I don't think we really need it. @tknopp for Gtk, @lobingera for Cairo, and I'm handling ColorTypes, Colors, and ColorVectorSpace (among many others in other organizations). Seem reasonable?

**Comment by timholy** [comment]
[attobot](https://github.com/attobot/attobot) is now on for this package; it does indeed make tagging releases much easier.

**Comment by tknopp** [comment]
yes fine with me. I was just referring to Cairo.jl

**Comment by lobingera** [comment]
(so back from some serious gardening...)
Yes, i can see the merge button (@timholy, can you give a rough timing of this change?) 

Picking up from above: I'll put a new PR for mesh grids - Including a message in Readme.md that you'll need cairo > 1.12.

**Comment by timholy** [comment]
> (@timholy, can you give a rough timing of this change?)

Months ago, I think. You probably have an invitation (one which you accepted) in your email, that might give you the date.

**Comment by cormullion** [comment]
@lobingera Great! I hope I haven't made too much (indoor "gardening") work for you! (I hope Cairo version 1.12 is old enough now to not be much of a problem.)

**Comment by lobingera** [comment]
see #175
