### ISSUE TITLE
Next Release (0.3.0)

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Cairo.jl#176]
not to forget
- [x]  #175 
- [x]  #167 
- [x] # 179 Compat 0.9.5, clarify cairo version on Readme.md, tkelman's comment about 1.8.8 on Centos6
- [x] get most 0.6 deprecations
- [x] test 0.6 badge (#178)
- [x] test coverage badge
- [x] #177, REQUIRE julia to 0.4

**Comment by cormullion** [comment]
Looking good!

**Comment by ararslan** [comment]
Note that since support for Julia 0.3 has been dropped, this will need to be a minor release per the METADATA (and semver) requirements. So this should be release 0.3.0 rather than 0.2.36.

**Comment by lobingera** [comment]
@ararslan Where are all these rules documented?

**Comment by lobingera** [comment]
https://github.com/JuliaLang/Compat.jl/issues/332

**Comment by ararslan** [comment]
TIL that wildcards in `Command` literals can be quoted using--wait for it--quotes. 😑

**Comment by ararslan** [comment]
Fix for shell quoting warnings: #181

**Comment by ararslan** [comment]
Is everything good for a 0.3.0 release now?

**Comment by ararslan** [comment]
Bump @lobingera

**Comment by lobingera** [comment]
@ararslan Tim Holy has a point with missing docstrings, and as this is a release i'd actually would have liked to deal (correctly) with the osx-only functions. But there is no show stopper anymore. I'll do some local testing.

**Comment by timholy** [comment]
As Tony Kelman says, version numbers are cheap. You can make releases in short succession.

**Comment by ararslan** [comment]
Thanks all!
