### ISSUE TITLE
Add docstrings

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/Cairo.jl#180]
Under @lobingera's excellent care, Cairo seems to making steady strides. Another big step forward would be to add docstrings, and possibly Documenter.jl documentation; I still find myself consulting the source pretty frequently.

If it's useful, anyone who wishes to help document Cairo is more than welcome to steal (and update) material from [this blogpost](http://julialang.org/blog/2013/05/graphical-user-interfaces-part2) (source is https://github.com/JuliaLang/julialang.github.com/blob/master/blog/_posts/2013-05-23-graphical-user-interfaces-part2.md) and/or the Gtk documentation.

**Comment by lobingera** [comment]
> I still find myself consulting the source pretty frequently.

Any specific? I'm just asking, because the 'main' cairo calls have just the C-API and only a small set is using multiple-inference.

**Comment by timholy** [comment]
More that it would be nice to be able to do `?Cairo` to be reminded about the main functions in this package, and then `?set_source` for more detail. For comparison, try `using Images; ?Images`.

Yes, one can consult the Cairo documentation, but that's slower than `?` and not possible if there's no wifi. Most often I just open `Cairo.jl` in an editor.
