### ISSUE TITLE
another Pkg.build("Cairo") issue

### ISSUE THREAD

**Issue by joachimdahl** [JuliaGraphics/Cairo.jl#184]
I have problems building Cairo, and I don't think this problem is covered in the other reports. 

On an Ubuntu 16.04.4 LTS server,  I am not able to build Cairo.

```
julia> Pkg.build("Cairo")
INFO: Building Cairo
=============================================================[ ERROR: Cairo ]==============================================================

LoadError: could not spawn `yum list libpng`: no such file or directory (ENOENT)
while loading /home/joachim/.julia/v0.5/Cairo/deps/build.jl, in expression starting on line 162

===========================================================================================================================================

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2470 v2 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

```
This is an odd error message, because the installer ought to fall back on apt-get and not yum.  But looking into the build.jl, the script seems to have the ability to download and build the relevant packages locally.  I don't understand it well enough to force a local build of required libraries, though.

**Comment by lobingera** [comment]
I'm not a BinDeps expert so i'm not sure why yum and not apt-get is called for missing dependencies on Ubuntu. 
1) Please run BinDeps.debug("Cairo") and post here.
2) Actually on a regular Ubuntu you should be able to install the dependencies on your own. I run a Ubunut desktop (14.04LTS) and never needed additional apt-gets.

**Comment by joachimdahl** [comment]
Here is the output.  I checked that libpng libraries (including dev packages) are installed on the server, but I suspect there is a naming conflict with the installation script.  On other machines I don't have admin privileges, though.
```
julia> BinDeps.debug("Cairo")
INFO: Reading build script...
The package declares 1 dependencies.
 - Library Group "cairo"ERROR: could not spawn `yum list libpng`: no such file or directory (ENOENT)
 in _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::Base.DevNullStream, ::Base.DevNullStream, ::Base.DevNullStream) at ./process.jl:321
 in #412 at ./process.jl:478 [inlined]
 in setup_stdio(::Base.##412#413{Cmd,Ptr{Void},Base.Process}, ::Tuple{Base.DevNullStream,Base.DevNullStream,Base.DevNullStream}) at ./process.jl:466
 in #spawn#411(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{Base.DevNullStream,Base.DevNullStream,Base.DevNullStream}, ::Bool, ::Bool) at ./process.jl:477
 in (::Base.#kw##spawn)(::Array{Any,1}, ::Base.#spawn, ::Cmd, ::Tuple{Base.DevNullStream,Base.DevNullStream,Base.DevNullStream}, ::Bool, ::Bool) at ./<missing>:0
 in package_available(::BinDeps.Yum) at /home/joachim/.julia/v0.5/BinDeps/src/dependencies.jl:143
 in can_provide(::BinDeps.Yum, ::Dict{Symbol,Any}, ::BinDeps.LibraryDependency) at /home/joachim/.julia/v0.5/BinDeps/src/dependencies.jl:651
 in #_find_library#50(::Type{T}, ::Function, ::BinDeps.LibraryDependency) at /home/joachim/.julia/v0.5/BinDeps/src/dependencies.jl:498
 in collect(::Base.Generator{Array{BinDeps.LibraryDependency,1},BinDeps.##53#54}) at ./array.jl:307
 in allf(::BinDeps.LibraryGroup) at /home/joachim/.julia/v0.5/BinDeps/src/dependencies.jl:665
 in show(::Base.TTY, ::BinDeps.LibraryGroup) at /home/joachim/.julia/v0.5/BinDeps/src/debug.jl:32
 in debug(::Base.TTY, ::String) at /home/joachim/.julia/v0.5/BinDeps/src/debug.jl:62
 in debug(::String) at /home/joachim/.julia/v0.5/BinDeps/src/debug.jl:65


```

**Comment by lobingera** [comment]
I opened a BinDeps issue as the debug output looks strange. As the dependencies are grouped, it might be that another library is missing, take a look at the list in build,jl.

**Comment by lobingera** [comment]
@joachimdahl 
I tried to recreate your situation. I installed (on a VM)

- ubuntu 16.04.2 LTS server
- julia 0.5.1 from downloads
- apt-get install libcairo2
- apt-get install libpng16-dev
- apt-get install gettext
- apt-get install libpango1.0-0

and could run Pkg.build and Pkg.test without complaints.

**Comment by joachimdahl** [comment]
OK, thank you for trying this.  I will try again with a clean installation
after Julia 0.6 is out.

**Comment by lobingera** [comment]
@joachimdahl Any news on that?

**Comment by joachimdahl** [comment]
No, I am waiting for version 0.6 final to be released.  Then I will build a
new version of Julia on our main server and update this thread.

On Mon, Apr 24, 2017 at 11:04 AM, Andreas Lobinger <notifications@github.com

**Comment by lobingera** [comment]
I see. Can you confirm, that you have both apt-get and yum installed?

**Comment by joachimdahl** [comment]
I did not realize that yum was a hard dependency. I don't have a qualified
opinion about whether or not this is a sensible depedency for an Ubuntu
server,  but it surprises me.  After installing yum, I am able to run
Pkg.build("Cairo") locally with success - many thanks!

On Mon, Apr 24, 2017 at 11:22 AM, Andreas Lobinger <notifications@github.com

**Comment by lobingera** [comment]
I file this under "false positive". I initially thought, on your system BinDeps confused between the packet managers, so i asked if you have apt-get and yum in parallel (which is highly unlikely on Ubuntu). No, yum should not be a hard dependency and BinDeps trying to run (spawn) yum to install a library that is available via apt-get is an error case. Just a last question: What did yum install?

**Comment by joachimdahl** [comment]
I removed yum and verified that Pkg.build("Cairo") fails.  Reinstalling yum
fixes that, the terminal output from apt-get is pasted below

root@karise:/home/joachim# apt-get install yum
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libsqlite0 python-libxml2 python-lzma python-rpm python-sqlite
python-sqlitecachec python-urlgrabber
Suggested packages:
  python-sqlite-dbg
The following NEW packages will be installed:
  libsqlite0 python-libxml2 python-lzma python-rpm python-sqlite
python-sqlitecachec python-urlgrabber yum
0 upgraded, 8 newly installed, 0 to remove and 37 not upgraded.

**Comment by lobingera** [comment]
I'm pretty convinced that this is an BinDeps only problem.
