### ISSUE TITLE
Getting font subpixel rendering to work

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaGraphics/Cairo.jl#199]
In the text examples the font do not use RGB subpixel rendering, I've tried to change that but with no success. From cairo doc it seem the only thing to do is to create a `cairo_font_options_t` struct and set its antialias option to `ANTIALIAS_SUBPIXEL` and then pass this to the cairo context. So I did something like that:

```julia
struct cairo_font_options_t end
options = ccall((:cairo_font_options_create,Cairo._jl_libcairo), Ptr{cairo_font_options_t}, ())
ccall((:cairo_font_options_set_antialias,Cairo._jl_libcairo), Void, (Ptr{cairo_font_options_t},Cint),options, Cairo.ANTIALIAS_SUBPIXEL)

set_font_options(cr,options) = ccall((:cairo_set_font_options,Cairo._jl_libcairo), Void,
(Ptr{Void},Ptr{cairo_font_options_t}),cr,options)
```

But that doesn't work for some reason, the font are antialiased (and using ANTIALIAS_NONE does disable it) but there's no RGB subpixel rendering. I have done something wrong here ?

https://gist.github.com/jonathanBieler/5a2b7494f79a3c164a59c67ba3c5028a

Note that it works in Gadfly, but as far as I can tell it's just calling `set_text`. Maybe the font loading part is the issue.

**Comment by lobingera** [comment]
1) how do you see that this is working in Gadfly?
2) how do you see that it isn't working in your example?

**Comment by jonathanBieler** [comment]
It's a bit hard to see at 100% zoom so I take a screenshot (or open the image) and zoom in.

It should look like bottom left but I only manage to get top left:

https://en.wikipedia.org/wiki/Subpixel_rendering#/media/File:Subpixel_demonstration_(Quartz).png

**Comment by lobingera** [comment]
Can you please attach your screenshots?

**Comment by jonathanBieler** [comment]
This is a label on a Gadfly plot (drawn on a Gtk surface):

https://imgur.com/BktvO5U

And this is the text example on a SDL surface with the font options as above:

https://imgur.com/Sc04Qiv

I've read a bit more about it and I think what's going on is that the surface also have a cairo_font_options_t (which could makes sense because RGB subpixel rendering depends on the screen) and that the one created with `cairo_image_surface_create_for_data` doesn't has subpixel rendering activated. That field is read-only so I cannot change it. Gtk gets its surface from another method. 

It's a bit weird because Cairo seems to have tests that does just what I do, but maybe there's something I don't quite understand.

https://github.molgen.mpg.de/git-mirror/cairo/blob/master/test/text-antialias-subpixel.c

**Comment by jonathanBieler** [comment]
I'm closing this, I don't think it's an issue with Cairo.jl.
