### ISSUE TITLE
Error on building Cairo on Windows machine

### ISSUE THREAD

**Issue by BoundaryValueProblems** [JuliaGraphics/Cairo.jl#207]
Hi. I'm trying to install Cairo on my windows machine (Windows 10: Fall Creator Update, i.e., the latest version; julia v0.6.1; Cairo v0.3.1), but failed. On my MacBook Pro, it worked without any problems. Here is the error messages I got on my windows machine. I would greatly appreciate your help!
```
INFO: Building Cairo
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.2/repodata/repomd.xml
INFO: Packages to update:  zlib1
INFO: Packages to install: libxml2-2, libwinpthread1, libpng16-16, libpixman-1-0, libfreetype6, libgcc_s_seh1, fontconfig, libharfbuzz0, libcairo2
INFO: Downloading: zlib1
INFO: Extracting: zlib1
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\xxx\.julia\v0.6\WinRPM\cache\2\noarch%2Fmingw64-zlib1-1.2.8-8.13.noarch.cpio

ERROR: Can not delete output file C:\Users\xxx\.julia\v0.6\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\zlib1.dll

Sub items Errors: 1


====================================================[ ERROR: Cairo ]====================================================

LoadError: failed process: Process(`'C:\Program Files\Julia-0.6.1\bin\7z.exe' x -y 'C:\Users\xxx\.julia\v0.6\WinRPM\cache\2\noarch%2Fmingw64-zlib1-1.2.8-8.13.noarch.cpio' '-oC:\Users\xxx\.julia\v0.6\WinRPM\deps'`, ProcessExited(2)) [2]
while loading C:\Users\xxx\.julia\v0.6\Cairo\deps\build.jl, in expression starting on line 162
```

**Comment by BoundaryValueProblems** [comment]
Well. I could resolve this problem manually. After I deleted the file ```C:\Users\xxx\.julia\v0.6\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\zlib1.dll``` by hand, I could run ```Pkg.build("Cairo")``` without any problems. However, a question still remains. Why the build command could not delete that offending old ```zlib1.dll``` file?

**Comment by lobingera** [comment]
@BoundaryValueProblems Handling of libraries and binaries is infrastructure provided by https://github.com/JuliaLang/BinDeps.jl.

**Comment by BoundaryValueProblems** [comment]
@lobingera Thanks! Then, should I post this issue at https://github.com/JuliaLang/BinDeps.jl?

**Comment by lobingera** [comment]
would make sense, however the case should be reproducable - which is usally a hard problem.
