### ISSUE TITLE
Cairo fails after upgrade

### ISSUE THREAD

**Issue by my-little-repository** [JuliaGraphics/Cairo.jl#212]
I just upgraded Cairo and now I get an error when I try to display images. 
I am using Cairo version 0.3.1 with Julia version 0.6.1. This bug is perhaps the reason why Winston does not work anymore, cf https://github.com/JuliaGraphics/Winston.jl/issues/285.

     julia> using Cairo
     julia> surf = CairoImageSurface(100, 200, Cairo.FORMAT_ARGB32)  # from the testset.
     ERROR: objects of type Cairo.#destroy cannot be finalized
     Stacktrace:
      [1] finalizer at ./base.jl:127 [inlined]
      [2] Type at ~/.julia/v0.6/Cairo/src/Cairo.jl:131 [inlined]
      [3] Type at ~/.julia/v0.6/Cairo/src/Cairo.jl:149 [inlined]
      [4] CairoImageSurface(::Int64, ::Int64, ::Int32) at ~/.julia/v0.6/Cairo/src/Cairo.jl:193

**Comment by lobingera** [comment]
This is/was handled in https://github.com/JuliaGraphics/Cairo.jl/pull/211 and will be tagged within this week.

**Comment by lobingera** [comment]
https://github.com/JuliaGraphics/Cairo.jl/releases/tag/v0.4.0
