### ISSUE TITLE
CairoScript should probably not use finalizers

### ISSUE THREAD

**Issue by andreasnoack** [JuliaGraphics/Cairo.jl#215]
At least on macOS 10.13.3, it seems that CairoScript only writes to the files [in this test](https://github.com/JuliaGraphics/Cairo.jl/blob/10913a18895481fd49ec661ff6c7a5730814e962/test/runtests.jl#L215-L218) when the finalizer is called. This might also what has caused the issues on Windows. My guess is that CairoScript shouldn't rely on finalizers but that the handle should be explicitly `destroy`ed every time.

**Comment by lobingera** [comment]
a) Could you please specify 'your Mac' further?
b) Did you see similar on travis?

libcairo documentation mentions anyway https://www.cairographics.org/manual/bindings-streams.html to use the stream implementation and do a language specific adaptation for files.
Strange here is, that e.g. SVG surface works and this uses almost the same c code in in libcairo

**Comment by andreasnoack** [comment]
I've updated the comment to include the macOS version. The issue is that this might randomly work if the gc runs before the file is read. It is completely unpredictable but might happen on Travis but not locally or the opposite. Locally, I was watching the file and exactly I executed `gc()` the file was written to.

**Comment by andreasnoack** [comment]
https://github.com/JuliaGraphics/Cairo.jl/issues/200 is what I hit here.

**Comment by lobingera** [comment]
I looked around a little bit and i agree with you, Script Surfaces should be explicitly destroyed.

**Comment by lobingera** [comment]
@andreasnoack Sorry for the confusion, but you confirmed, that you saw this problem like in #200, the test for file existence is true, the check for length and content is failing? And you can confirm, that only the gc call writes the file, but not the destroy call? 
Do you have any output/log available?

**Comment by andreasnoack** [comment]
> the test for file existence is true, the check for length and content is failing?

Yes

> And you can confirm, that only the gc call writes the file, but not the destroy call?

Yes

> Do you have any output/log available?

No and I'm not sure what you had in mind. The way I confirmed this was to `tail -f a.cs` in a separate window. This worked, i.e. the file had been created. Then I called destroy and nothing happened. Finally, the call to `gc` triggered the write.

**Comment by lobingera** [comment]
With https://github.com/JuliaGraphics/Cairo.jl/pull/251 CairoScript Surface feature is reduced to stream only, which is recommended by libcairo documentation anyway and seems to test fine.
