### ISSUE TITLE
Update AppVeyor badge in README.md

### ISSUE THREAD

**Issue by andreasnoack** [JuliaGraphics/Cairo.jl#217]
It points to the wrong account. I think you'll have to be admin to get the right badge url which is why this is not a PR.

**Comment by ararslan** [comment]
Whose account should it point to? Organizations can't have dedicated AppVeyor accounts like Travis; each repo has to be run on someone's personal AV account.

**Comment by andreasnoack** [comment]
It should point to this account behind https://ci.appveyor.com/project/JuliaGraphics/cairo-jl/build/1.0.159, since that is the one getting triggered by PRs here. The one behind the current badge hasn't run for a long time.

**Comment by ararslan** [comment]
There is a way to get a generic link for any open source project running on AppVeyor without the owner needing to specifically fetch the URL from the web UI. Let me see if I can find a repo that uses it.

**Comment by ararslan** [comment]
[![AppVeyor](https://ci.appveyor.com/api/projects/status/github/JuliaGraphics/cairo-jl/branch/master?svg=true)](https://ci.appveyor.com/project/JuliaGraphics/cairo-jl/branch/master)

```
[![AppVeyor](https://ci.appveyor.com/api/projects/status/github/JuliaGraphics/cairo-jl/branch/master?svg=true)](https://ci.appveyor.com/project/JuliaGraphics/cairo-jl/branch/master)
```
Hm, not sure why the badge says unknown...

**Comment by lobingera** [comment]
@andreasnoack If i click on the provided link, i end up in my own appveyor project, so on my account. And the settings say: watch master. I have no good idea why it wasn't started automatically with the last merge.

**Comment by andreasnoack** [comment]
This issue is not fixed

**Comment by lobingera** [comment]
@andreasnoack Do you have an example of a project with 'a' correct setting?

**Comment by lobingera** [comment]
@JuliaGraphics/collaborators Anyone here with the access for travis-CI for the organisation?

**Comment by ararslan** [comment]
I have access to Travis but not AppVeyor. (I assume you meant AppVeyor?)

**Comment by lobingera** [comment]
@ararslan So could you please provide the correct badge? Copy here and i'll put it into the readme, or just put it there yourself.

**Comment by ararslan** [comment]
I'm not sure what the correct badge is, or I already would have. :wink:

**Comment by lobingera** [comment]
@andreasnoack Can you help us?

**Comment by andreasnoack** [comment]
It's a very peculiar situation. I'd also just opened a PR with the right badge if I knew how to get it but apparently, it is only persons with access the team account that can get the right link to the badge and we don't know who has access and we don't know how to figure it out. I guess we could either contact AppVeyor and ask them or @lobingera could see if he could enable testing on his account again such that the current badge gets updated.

**Comment by lobingera** [comment]
i see, @ararslan if you log-in into appveyor, are you connected to JuliaGraphics, or your own account?

**Comment by ararslan** [comment]
My own account.

**Comment by lobingera** [comment]
@JuliaGraphics

So. I contacted appveyor help https://help.appveyor.com/discussions/problems/13989-build-doesnt-start and learned that i do not have enough rights to setup and debug this.

Option 1): Someone raises my status to 'Owner'
Option 2): Someone with enough rights debugs this.

**Comment by lobingera** [comment]
Hello, can someone of the list of recipients please raise my status to 'Owner' so i can work on this?

@ararslan, @cormullion,@barche,@Keno, @oxinabox, @SimonDanisch, @timholy 

Thanks in advance.

**Comment by ararslan** [comment]
Looks like Keno updated your permissions, so you should have admin rights now.

**Comment by lobingera** [comment]
So. After some tests i did:

* create a new, dedicated project in appveyor (on my name) -> https://ci.appveyor.com/project/lobingera/cairo-jl-f7sfx
* manually reconfigured the webhook

Looks like this is working now (however not passing as win64 seem failing)
