### ISSUE TITLE
points for major release

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Cairo.jl#218]
- [ ]  split src/Cairo into reasonable files
- [x]  work on stable ScriptSurface closing (destroy?)
- [x]  deprecation warning on undef
- [x]  deprecation warning on cfunction
- [ ]  deprecation warning on srand
- [ ]  deprecation warning on next 
- [x]  full appveyor CI

**Comment by cormullion** [comment]
Any chance of fixing these dep warnings soon? Documenter files like to include these warnings in the text of the documentation... ;)

```
┌ Warning: The function `cfunction` is now written as a macro `@cfunction`.
│   caller = get_stream_callback at Cairo.jl:145 [inlined]
└ @ Core ~/.julia/packages/Cairo/byAsC/src/Cairo.jl:145
```

eg in  http://juliagraphics.github.io/Luxor.jl/latest/text.html.

**Comment by lobingera** [comment]
i hoped femtocleaner has something for that. Simply adding a at-sign creates problems in v0.6
