### ISSUE TITLE
Labels not showing up in ProfileView

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaGraphics/Cairo.jl#223]
See https://github.com/timholy/ProfileView.jl/issues/91. I'm opening an issue here because pinning Cairo to 0.4 fixes the issue.

**Comment by lobingera** [comment]
I could reproduce this, locally with linux, julia 062. As GtkReactive shows no fail messages or errors on importing, it might be hard to debug.

**Comment by timholy** [comment]
Fixed by #254
