### ISSUE TITLE
_jl_libcairo still not defined

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaGraphics/Cairo.jl#232]
I have tried the "solutions" posted in #165 and https://github.com/JuliaPackaging/Homebrew.jl/issues/189 to no avail. In julia 0.6, Cairo builds and then throws the following error on precompile
```julia
julia> using Cairo
INFO: Precompiling module Cairo.
ERROR: LoadError: UndefVarError: _jl_libcairo not defined
Stacktrace:
 [1] anonymous at ./<missing>:?
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /Users/Mikael/.julia/v0.6/Cairo/src/Cairo.jl, in expression starting on line 19
ERROR: Failed to precompile Cairo to /Users/Mikael/.julia/lib/v0.6/Cairo.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405

```
One would think that less *ad hoc* solutions would have been implemented by now.

**Comment by MikaelSlevinsky** [comment]
I found the current fix in #231
```julia
using Homebrew
Homebrew.brew(`reinstall fontconfig`)
Pkg.build("Cairo")
using Cairo # works
```

**Comment by gtollefson** [comment]
I get the same error as the OP but also have an error from this fix.

Error:
> julia> using Cairo
INFO: Precompiling module Cairo.
ERROR: LoadError: UndefVarError: _jl_libcairo not defined

I've tried this fix but receive an error which I've posted below.
```
using Homebrew
Homebrew.brew(`reinstall fontconfig`)
Pkg.build("Cairo")
using Cairo
```

> julia> using Homebrew
> 
> julia> Homebrew.brew(`reinstall fontconfig`)
> ==> Reinstalling fontconfig 
> ==> Downloading https://www.freedesktop.org/software/fontconfig/release/fontconf
> Already downloaded: /Users/George/Library/Caches/Homebrew.jl/downloads/707a631c311b2e5c4cf1797f81dba360fe6147b5f49a1797547d8c768a8bde71--fontconfig-2.13.1.tar.bz2
> ==> ./configure --disable-silent-rules --enable-static --with-add-fonts=/System/
> ==> make install RUN_FC_CACHE_TEST=false
> ==> Regenerating font cache, this may take a while
> ==> /Users/George/.julia/test/v0.6/Homebrew/deps/usr/Cellar/fontconfig/2.13.1/bi
> Error: Cannot link fontconfig
> Another version is already linked: /Users/George/.julia/test/v0.6/Homebrew/deps/usr/Cellar/fontconfig/2.13.1
> ERROR: failed process: Process(`/Users/George/.julia/test/v0.6/Homebrew/deps/usr/bin/brew reinstall fontconfig`, ProcessExited(1)) [1]
> Stacktrace:
>  [1] pipeline_error(::Base.Process) at ./process.jl:682
>  [2] run(::Cmd) at ./process.jl:651
>  [3] #brew#4(::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Function, ::Cmd) at /Users/George/.julia/test/v0.6/Homebrew/src/API.jl:19
>  [4] brew(::Cmd) at /Users/George/.julia/test/v0.6/Homebrew/src/API.jl:11

**Comment by terasakisatoshi** [comment]
Same problem occurs on my RaspberryPi3 

- Julia v1.0.3
- Cairo v0.5.6

```
ulia> using Cairo
INFO: Precompiling module Cairo.
ERROR: LoadError: UndefVarError: _jl_libcairo not defined
```

**Comment by ryamauti** [comment]
I got this error on Atom under Windows.
Running Atom in administrator mode solved for me:
`import Pkg
Pkg.build("Cairo")`
