### ISSUE TITLE
0.7 strategy

### ISSUE THREAD

**Issue by davidanthoff** [JuliaGraphics/Cairo.jl#235]
I'm starting to wonder whether it might be easier to drop 0.6 support on ``master``. That seems to be what most packages are doing right now because it seems a lot more complicated to support both 0.6 and 0.7 at the same time than I originally thought...

It doesn't mean julia 0.6 support would stop. There would still be a last tagged release for 0.6, and we could still release bug fix releases for 0.6 if needed as patch releases.

**Comment by tknopp** [comment]
Should make a 0.6 branch then

**Comment by davidanthoff** [comment]
I would just follow the strategy that pretty much all other packages use right now:
1) make ``master`` 0.7 only
2) tag a release off master that is 0.7 compatible
3) Don't do anything else for now.

If it turns out that there is a need for another bug fix release for 0.6, create a branch off the last tag that worked on 0.6, fix the bug there, create a tag on that branch. But I don't think we need to spend time on setting that stuff up right now, that can really wait until the need for a bug fix actually shows up.

**Comment by davidanthoff** [comment]
Also, julia 0.7 final was just released, so it would be really great to get a release out that works on that.

**Comment by davidanthoff** [comment]
Although, maybe we don't need this, I think I have another PR that fixes all remaining things and also works on 0.6....

**Comment by davidanthoff** [comment]
I think we should tag a release at this point. Right now tests pass on Linux (all julia versions), Windows (julia 0.6 & 0.7). They don't pass on Mac because Homebrew.jl is broken, but as far as I can tell that is also the case with the currently shipping version, so that doesn't look like a regression to me.

Tagging now would mean we have a working version for 0.7 on linux and windows, which would allow depending packages to move on with their compat work.

@lobingera Does that sound reasonable to you? My main worry is that I don't see a strategy that would address the Homebrew.jl issue anytime soon, and I feel that shouldn't hold back a new release on all the other platforms.

**Comment by tknopp** [comment]
+1 for a release. It does not hurt anyway since the issue is present on 0.6 as well.

**Comment by lobingera** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/16455

I've seen Compat has now rand(seed and maybe unwrap_safe and iterate/next are easy to get.
