### ISSUE TITLE
Rename appveyor project

### ISSUE THREAD

**Issue by davidanthoff** [JuliaGraphics/Cairo.jl#236]
@lobingera Can you rename the appveyor project to ``Cairo.jl``? You need to do that in the settings of the project on the appveyor webpage. Without that the new default julia appveyor script doesn't run and it gets really tricky to try to fix this package for 0.7 without that. Should really be a 1 minute thing only.

**Comment by lobingera** [comment]
I just did. However as i have/had more than 1 Cairo in appveyor this was some complicated (to setup). Let's see if simple renaming works ...

**Comment by davidanthoff** [comment]
I think that works now!
