### ISSUE TITLE
Tests fail on Julia 1.0

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGraphics/Cairo.jl#241]
.travis.yml not currently testing for Julia 1.0 - but noticed a failure on InspectDR tests (https://github.com/ma-laforge/InspectDR.jl).

I would do a PR for .travis.yml, but the matrix looks a little over-specific to me.  Wondering if it would not be better to simplify things.

**Comment by tknopp** [comment]
fixed in #244, thanks
