### ISSUE TITLE
Cairo builds on 1.0 but not nightly

### ISSUE THREAD

**Issue by timholy** [JuliaGraphics/Cairo.jl#253]
I don't have time to dig into this now, but it's a little alarming. See the `nightly` test failures in https://github.com/JuliaGizmos/GtkReactive.jl/pull/76.

**Comment by lobingera** [comment]
i just added nightly to .tavis.yml for linux, let's see...

**Comment by staticfloat** [comment]
This was my fault; I broke `dlsym()` and `dlopen()`.  Fix awaiting in https://github.com/JuliaLang/julia/pull/28953

**Comment by lobingera** [comment]
Passed on nightly - Julia Version 1.1.0-DEV.160
Commit f77c36bc75 (2018-09-02 11:27 UTC)
