### ISSUE TITLE
Cairo doesn't build on macOS Mojave

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Cairo.jl#263]
due to https://github.com/JuliaGraphics/Fontconfig.jl/issues/21 I expect

**Comment by cormullion** [comment]
It's not Fontconfig but fontconfig... Sorry.

**Comment by CiaranOMara** [comment]
To clarify, Cairo.jl does not use Fontconfig.jl, but uses BinDeps to roll their own fontconfig.
