### ISSUE TITLE
Cairo renders to Juno's Plot Pane

### ISSUE THREAD

**Issue by kraftpunk97** [JuliaGraphics/Cairo.jl#276]
Hello. I'm new to Cairo and `Cairo.jl`. Is it possible for me to render an image to Juno's plot pane? If so, then how do I do that?

**Comment by lobingera** [comment]
http://docs.junolab.org/latest/man/info_developer/#Displaying-Plots-and-Graphics-1
lists a few input formats for the juno pane. png and svg are simple to do in Cairo.jl

**Comment by kraftpunk97** [comment]
Thank you very much
