### ISSUE TITLE
Trouble using save and restore functions

### ISSUE THREAD

**Issue by kraftpunk97** [JuliaGraphics/Cairo.jl#278]
Hello. I wrote the following script using `Cairo.jl`.
```Julia
using Cairo


screen_width = 600
screen_height = 400

c = CairoRGBSurface(screen_width, screen_height)
cr = CairoContext(c)


set_source_rgb(cr, 1, 1, 1)
rectangle(cr,0.0,0.0,screen_width,screen_height); # background
fill(cr);
save(cr);


ctx = CairoContext(c);
rectangle(ctx, 13, 0, 30f0, 30f0)
set_fill_type(ctx, Cairo.CAIRO_FILL_RULE_EVEN_ODD)
set_source_rgb(ctx, 1, 0, 0)
fill_preserve(ctx)

restore(cr)

display(c)
```
I expected to get a blank white output screen. However, the red box at the top of the screen was still present when I called `display`. I don't understand what is happening here.

**Comment by lobingera** [comment]
I didn't run the code, but as far as i can see:
* setup of a surface
* using a context of cr to fill all white
* using a context of ctx to fill a smaller rectangle with red
* restore the previous context of cr
See surfaces as the area where you draw and contexts as state for drawing. 
Why do you expect a 'blank white screen'?

**Comment by kraftpunk97** [comment]
By "blank white screen", I meant a surface of dimensions `screen_width*screen_heigth`, that was all white, sorry for the confusion. I expected this because I saved the state after painting the surface white and called `restore` after I drew a small rectangle. It was my understanding that calling restore on a Context after it has been saved undid all changes made from the save until the last actoin

**Comment by kraftpunk97** [comment]
pinging @lobingera

**Comment by lobingera** [comment]
Sorry, i thought the answer was implicit clear. The context is saving the state of your drawing/rendering like color, coordinate transformation, font, backend etc, but NOT your drawing. Just see a surface as piece of paper. Once you've drawn something there, you can overpaint it (e.g in white) but you cannot delete.

**Comment by kraftpunk97** [comment]
@lobingera I see! When I call `save` after making certain changes to a context and if I later call `restore` after making further changes, all the changes made to the **context** after the save are voided?

**Comment by lobingera** [comment]
Yes.
