### ISSUE TITLE
get_current_point?

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Cairo.jl#282]
Is there a `get_current_point` feature in Cairo? If there is, could it be added safely to Cairo.jl?

**Comment by lobingera** [comment]
https://www.cairographics.org/manual/cairo-Paths.html#cairo-get-current-point

If we can live with double (i.e. float64) output only, it should be easy to add.

**Comment by cormullion** [comment]
👍🏻 I like Float64 fine!

**Comment by lobingera** [comment]
> The current point is returned in the user-space coordinate system. If there is no defined current point or if cr is in an error status, x and y will both be set to 0.0. It is possible to check this in advance with cairo_has_current_point().

Like this?

**Comment by cormullion** [comment]
`has_current_point()` would also be useful.

**Comment by cormullion** [comment]
Great!

**Comment by lobingera** [comment]
is in master and probably be part of next release.
