### ISSUE TITLE
Fails to build Cairo on Windows - Julia 1.1

### ISSUE THREAD

**Issue by mathis-g** [JuliaGraphics/Cairo.jl#284]
Hello everyone,

I wanted to install the ImageView package on Julia 1.1 on Windows 10, which requires Cairo and Gtk. But both Cairo and Gtk fail to build. Apparently, this is not a new problem, there has been some issues with older versions of Julia, two or three years ago, and the issue came back on Mac around March of this year : #271. But according to this post, at that time it worked on Windows. There is also some people who wanted it to run on Windows 7 : #265, but their way of solving the problem do not work with me, and they also say it worked on Windows 10. I also tried to remove environment variables like in #261 but this did not work.
So is this a problem with my computer or is this due to some recent update ?

When I execute `using ImageView`, I got : 
`ERROR: LoadError: LoadError: error compiling top-evel scope: could not load library "libgobject-2.-0"
The specified module could not be found.`

So I tried `Pkg.build("ImageView")`, and I got this : 

┌ Error: Error building `Cairo`:
│ [ Info: Updating WinRPM package list
│ [ Info: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/repodata/repomd.xml
│ ┌ Warning: Unknown download failure, error code: 2148270086
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/repodata/repomd.xml
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ [ Info: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_Leap_42.3/repodata/repomd.xml
│ [ Info: Nothing to do
│ ERROR: LoadError: Provider WinRPM.RPM failed to satisfy dependency cairo
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at C:\Users\Mathis\.julia\packages\BinDeps\ZEval\src\dependencies.jl:945
│  [3] satisfy!(::BinDeps.LibraryGroup, ::Array{DataType,1}) at C:\Users\Mathis\.julia\packages\BinDeps\ZEval\src\dependencies.jl:910
│  [4] satisfy!(::BinDeps.LibraryGroup) at C:\Users\Mathis\.julia\packages\BinDeps\ZEval\src\dependencies.jl:874
│  [5] top-level scope at C:\Users\Mathis\.julia\packages\BinDeps\ZEval\src\dependencies.jl:977
│  [6] include at .\boot.jl:326 [inlined]
│  [7] include_relative(::Module, ::String) at .\loading.jl:1038
│  [8] include(::Module, ::String) at .\sysimg.jl:29
│  [9] include(::String) at .\client.jl:403
│  [10] top-level scope at none:0
│ in expression starting at C:\Users\Mathis\.julia\packages\Cairo\p68X8\deps\build.jl:176
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075
  Building Gtk ─────────────→ `C:\Users\Mathis\.julia\packages\Gtk\aP55V\deps\build.log`
┌ Error: Error building `Gtk`:
│ ┌ Warning: Package not found that provides rpm
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides /bin/sh
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides /bin/bash
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ [ Info: Multiple package candidates found for mingw32(libjpeg-8.dll), picking newest.
│ ┌ Warning: Package not found that provides libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libstdc++.so.6(CXXABI_1.3)(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libm.so.6(GLIBC_2.2.5)(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libstdc++.so.6(GLIBCXX_3.4.10)(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libc.so.6(GLIBC_2.14)(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libstdc++.so.6()(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libstdc++.so.6(GLIBCXX_3.4)(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libgcc_s.so.1(GCC_3.0)(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libgcc_s.so.1()(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Warning: Package not found that provides libm.so.6()(64bit)
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:298
│ ┌ Info: Packages to update:
│ └   join(names(toup), ", ") = "pango-tools, gtk2-tools, gtk3-tools, glib2-tools"
│ ┌ Info: Packages to install:
│ └   join(names(todo), ", ") = "mingw32-cross-breakpad-tools, filesystem"
│ ┌ Info: Downloading:
│ └   name = "pango-tools"
│ ┌ Info: Extracting:
│ └   name = "pango-tools"
│ ┌ Info: Downloading:
│ └   name = "gtk2-tools"
│ ┌ Warning: Unknown download failure, error code: 2148270086
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 1/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/noarch/mingw32-gtk2-tools-2.24.32-1.26.noarch.rpm│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270086
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 2/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/noarch/mingw32-gtk2-tools-2.24.32-1.26.noarch.rpm│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270086
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 3/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/noarch/mingw32-gtk2-tools-2.24.32-1.26.noarch.rpm│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270086
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 4/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/noarch/mingw32-gtk2-tools-2.24.32-1.26.noarch.rpm│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ ┌ Warning: Unknown download failure, error code: 2148270086
│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:68
│ ┌ Warning: Retry 5/5 downloading: https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/noarch/mingw32-gtk2-tools-2.24.32-1.26.noarch.rpm│ └ @ WinRPM C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:70
│ [ Info: try running WinRPM.update() and retrying the install
│ ERROR: LoadError: failed to download gtk2-tools 0 from https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_Leap_42.3/noarch/mingw32-gtk2-tools-2.24.32-1.26.noarch.rpm.
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] do_install(::WinRPM.Package) at C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:469
│  [3] do_install at C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:456 [inlined]
│  [4] #install#19(::Bool, ::Function, ::WinRPM.Packages{Array{LibExpat.ETree,1}}) at C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:400│  [5] #install at .\none:0 [inlined]
│  [6] #install#18(::Bool, ::Function, ::Array{String,1}, ::String) at C:\Users\Mathis\.julia\packages\WinRPM\Y9QdZ\src\WinRPM.jl:379│  [7] #install at .\none:0 [inlined] (repeats 2 times)
│  [8] top-level scope at C:\Users\Mathis\.julia\packages\Gtk\aP55V\deps\build.jl:30│  [9] include at .\boot.jl:326 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1038│  [11] include(::Module, ::String) at .\sysimg.jl:29│  [12] include(::String) at .\client.jl:403
│  [13] top-level scope at none:0
│ in expression starting at C:\Users\Mathis\.julia\packages\Gtk\aP55V\deps\build.jl:24└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win32\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075

Thank you !

**Comment by YermolenkoIgor** [comment]
Try this:
https://github.com/JuliaGraphics/Cairo.jl/issues/265#issuecomment-460310469
