### ISSUE TITLE
Working with RGB arrays.

### ISSUE THREAD

**Issue by kraftpunk97** [JuliaGraphics/Cairo.jl#285]
Hi. I was wondering if it's possible to process RGB arrays as images in Cairo. For example, if I am to take an `Array{UInt8, 3}`, how would I get it to display on my screen?

**Comment by lobingera** [comment]
CairoImageSurface accepts an Array{UInt32,2} or Matrix{T}) where {T<:Union{RGB24,ARGB32}}. So you only need to provide your data in that form. Images.jl https://juliaimages.org/latest/  or Colors.jl https://github.com/JuliaGraphics/Colors.jl can be used to convert. In https://github.com/JuliaGraphics/Cairo.jl/blob/master/samples/sample_alpha_paint.jl#L11-L20 a simple 2x2 pattern is build.

**Comment by kraftpunk97** [comment]
Got it. Thank you.
