### ISSUE TITLE
Error building Cairo with Window 10

### ISSUE THREAD

**Issue by Silverfox28** [JuliaGraphics/Cairo.jl#299]
When I try to install

add https://github.com/BenLauwens/ThinkJulia.jl
![Annotazione 2019-09-29 174854](https://user-images.githubusercontent.com/7389330/65835042-cd378e80-e2e1-11e9-9ea3-d7904841c2ad.png)

**Comment by giordano** [comment]
This is a problem in BinaryProvider, this should be tracked in https://github.com/JuliaPackaging/BinaryProvider.jl/issues/172 if I got correctly

**Comment by NicholasWMRitchie** [comment]
It will build if you are an open your Julia shell with Adminstrator priviledges and issue a 'build Cairo' command. (My experience on Win10 Enterprise...)

**Comment by Silverfox28** [comment]
I solved by setting Windows 10 in developer mode

**Comment by giordano** [comment]
Fixed by https://github.com/JuliaGraphics/Cairo.jl/pull/301
