### ISSUE TITLE
Exported values do not exist.

### ISSUE THREAD

**Issue by pixel27** [JuliaGraphics/Cairo.jl#319]
In constants.jl line 4 there is:
```
export CAIRO_FORMAT_ARGB32,
    CAIRO_FORMAT_RGB24,
    CAIRO_FORMAT_A8,
    CAIRO_FORMAT_A1,
    CAIRO_FORMAT_RGB16_565,
    CAIRO_CONTENT_COLOR,
    CAIRO_CONTENT_ALPHA,
    CAIRO_CONTENT_COLOR_ALPHA,
    CAIRO_FILTER_FAST,
    CAIRO_FILTER_GOOD,
    CAIRO_FILTER_BEST,
    CAIRO_FILTER_NEAREST,
    CAIRO_FILTER_BILINEAR,
    CAIRO_FILTER_GAUSSIAN
```
However NONE of those values are actually defined in any of the source files.  My guess is that the original constants got the CAIRO_ part dropped but the export wasn't updated?  However line 3 has the comment:
```
# deprecated exports---do not add more!
```
So now I'm worried about how to create an A1 surface.  What I'm doing is:
```
CairoImageSurface(width, height, Cairo.FORMAT_A1)
```
But if the constants are deprecated....I'm not sure that is the right solution.

I was also going to create a pull request, but because of the line 3 comment I'm not sure if the desired solution is to remove the export line or update what is exported.

**Comment by lobingera** [comment]
I think the comment means: Don't add to this block. 
You use the correct constant.

**Comment by pixel27** [comment]
Thank you.
