### ISSUE TITLE
segfaults on v1.5.0-beta1

### ISSUE THREAD

**Issue by yakir12** [JuliaGraphics/Cairo.jl#323]
The following line seems to be causing segfaults in Julia version v1.5.0-beta1 (see https://github.com/JuliaPlots/Makie.jl/issues/627):
https://github.com/JuliaGraphics/Cairo.jl/blob/25f5658c9b70075bd3f1a781febc5a38c5cbd002/src/Cairo.jl#L158

Besides, it seems strange to predicate on a literal `false`?

**Comment by giordano** [comment]
> Besides, it seems strange to predicate on a literal `false`?

That should probably be replaced with `unsafe_write(s,buf,len)`, it's a leftover from v0.5 times: https://github.com/JuliaGraphics/Cairo.jl/commit/b8ea3a0b384b842880e341e71b44b23d04d34fc2

**Comment by lobingera** [comment]
agree.

**Comment by lobingera** [comment]
I don't fully understand why only 6 or 8 tests pass
