### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaGraphics/Cairo.jl#328]
Could someone please tag a version with the pointer fixes merged recently for Julia 1.5? I'd like to depend on that version with CairoMakie so we can use 1.5 and onwards.

**Comment by lobingera** [comment]
https://github.com/JuliaGraphics/Cairo.jl/releases/tag/v1.0.4

**Comment by lobingera** [comment]
@JuliaRegistrator register

**Comment by lobingera** [comment]
@JuliaRegistrator register

**Comment by lobingera** [comment]
@JuliaRegistrator register

**Comment by lobingera** [comment]
@JuliaRegistrator register

**Comment by jkrumbiegel** [comment]
thanks!
