### ISSUE TITLE
Access current font size

### ISSUE THREAD

**Issue by Wikunia** [JuliaGraphics/Cairo.jl#330]
It's currently not possible to get the current font size, right?
I assume it's possible to do this with: https://www.cairographics.org/manual/cairo-text.html#cairo-get-font-matrix
Maybe someone can help me with creating a PR for that. 
Unfortunately I haven't worked with Cairo or `ccall` before :smile: so I'm a bit lost

**Comment by lobingera** [comment]
It should be very close to 
https://github.com/JuliaGraphics/Cairo.jl/blob/master/src/Cairo.jl#L1096-L1119
which is the operations on the context's matrix.
