### ISSUE TITLE
Load error of Cairo: ERROR: LoadError: LoadError: InitError: could not load library

### ISSUE THREAD

**Issue by bulbulahmmed** [JuliaGraphics/Cairo.jl#335]
I am using MacOS Mojave version 10.14.6
I can build Cairo. When I try to import it, I found this:
[ Info: Precompiling Cairo [159f3aea-2a34-519c-b102-8c37f9878175]
ERROR: LoadError: LoadError: InitError: could not load library "/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/libicudata.67.1.dylib"
dlopen(/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/libicudata.67.1.dylib, 1): image not found
Stacktrace:
 [1] dlopen(::String, ::UInt32; throw_error::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
 [2] dlopen(::String, ::UInt32) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
 [3] macro expansion at /Users/bulbulahmmed/.julia/packages/JLLWrappers/KuIwt/src/products/library_generators.jl:61 [inlined]
 [4] __init__() at /Users/bulbulahmmed/.julia/packages/ICU_jll/1D38D/src/wrappers/x86_64-apple-darwin.jl:13
 [5] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
 [6] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:782
 [7] _require(::Base.PkgId) at ./loading.jl:1007
 [8] require(::Base.PkgId) at ./loading.jl:928
 [9] require(::Module, ::Symbol) at ./loading.jl:923
 [10] include(::Function, ::Module, ::String) at ./Base.jl:380
 [11] include(::Module, ::String) at ./Base.jl:368
 [12] top-level scope at /Users/bulbulahmmed/.julia/packages/JLLWrappers/KuIwt/src/toplevel_generators.jl:170
 [13] include(::Function, ::Module, ::String) at ./Base.jl:380
 [14] include(::Module, ::String) at ./Base.jl:368
 [15] top-level scope at none:2
 [16] eval at ./boot.jl:331 [inlined]
 [17] eval(::Expr) at ./client.jl:467
 [18] top-level scope at ./none:3
during initialization of module ICU_jll
in expression starting at /Users/bulbulahmmed/.julia/packages/HarfBuzz_jll/OFN8Y/src/wrappers/x86_64-apple-darwin.jl:11
in expression starting at /Users/bulbulahmmed/.julia/packages/HarfBuzz_jll/OFN8Y/src/HarfBuzz_jll.jl:8
ERROR: LoadError: LoadError: Failed to precompile HarfBuzz_jll [2e76f6c2-a576-52d4-95c1-20adfe4de566] to /Users/bulbulahmmed/.julia/compiled/v1.5/HarfBuzz_jll/h60co_TAMtb.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
 [6] include(::Function, ::Module, ::String) at ./Base.jl:380
 [7] include(::Module, ::String) at ./Base.jl:368
 [8] top-level scope at /Users/bulbulahmmed/.julia/packages/JLLWrappers/KuIwt/src/toplevel_generators.jl:170
 [9] include(::Function, ::Module, ::String) at ./Base.jl:380
 [10] include(::Module, ::String) at ./Base.jl:368
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:331 [inlined]
 [13] eval(::Expr) at ./client.jl:467
 [14] top-level scope at ./none:3
in expression starting at /Users/bulbulahmmed/.julia/packages/Pango_jll/XQBSg/src/wrappers/x86_64-apple-darwin.jl:8
in expression starting at /Users/bulbulahmmed/.julia/packages/Pango_jll/XQBSg/src/Pango_jll.jl:8
ERROR: LoadError: Failed to precompile Pango_jll [36c8627f-9965-5494-a995-c6b170f724f3] to /Users/bulbulahmmed/.julia/compiled/v1.5/Pango_jll/lZI8Y_TAMtb.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
 [6] include(::Function, ::Module, ::String) at ./Base.jl:380
 [7] include(::Module, ::String) at ./Base.jl:368
 [8] top-level scope at none:2
 [9] eval at ./boot.jl:331 [inlined]
 [10] eval(::Expr) at ./client.jl:467
 [11] top-level scope at ./none:3
in expression starting at /Users/bulbulahmmed/.julia/packages/Cairo/smWIA/src/Cairo.jl:8
ERROR: Failed to precompile Cairo [159f3aea-2a34-519c-b102-8c37f9878175] to /Users/bulbulahmmed/.julia/compiled/v1.5/Cairo/l6vnT_TAMtb.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923

**Comment by giordano** [comment]
Does this happen in a fresh session or did you load other packages before trying to use `Cairo.jl`?

After you get this error, in the same session please do
```julia
using Pkg
Pkg.add("DependencyWalker")
using DependencyWalker
Library("/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/libicudata.67.1.dylib")
```
and report here the output.  **Please, quote the code**: you can do it by clicking on the `<>` button in the toolbar of the comment here on GitHub.  This makes reading the code you post much easier for who wants to help you.

**Comment by bulbulahmmed** [comment]
Hi Giordano,
It happens all time.
I used your codes and found that the .dylib is not found. Please see below:

`using Pkg
using DependencyWalker
[ Info: Precompiling DependencyWalker [7db386b5-e858-4964-8eb4-2fa66f8df882]
Library("/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/libicudata.67.1.dylib")
✗ /Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/libicudata.67.1.dylib (NOT FOUND)`

**Comment by giordano** [comment]
That's strange, try with
```julia
using DependencyWalker
Library("/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/libicudata.67.dylib")
```
Remember to run this _after_ you get the error in the same Julia session.

**Comment by bulbulahmmed** [comment]
Hi Giordano,
I did exactly what you have mentioned in your comments. 
Also, I checked actual directory and I have not found the libicudata.67.1.dylib file.
Actual directory looks like this

    /Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/icu/67.1/

67.1 / directory has Makefile.inc and pkgdata.inc but not the libicudata.67.1.dylib file.

**Comment by giordano** [comment]
> Hi Giordano,
> I did exactly what you have mentioned in your comments.

I don't see the output of the command

```julia
Library("/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/libicudata.67.dylib")
```

I suggested above.

> Also, I checked actual directory and I have not found the libicudata.67.1.dylib file.

That's not possible, this should be the structure of `/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/` directory:
```
% tree
.
├── bin
│   ├── derb
│   ├── genbrk
│   ├── gencfu
│   ├── gencnval
│   ├── gendict
│   ├── genrb
│   ├── icu-config
│   ├── icuinfo
│   ├── makeconv
│   ├── pkgdata
│   └── uconv
├── include
│   └── unicode
│       ├── alphaindex.h
│       ├── appendable.h
│       ├── basictz.h
│       ├── brkiter.h
│       ├── bytestream.h
│       ├── bytestriebuilder.h
│       ├── bytestrie.h
│       ├── calendar.h
│       ├── caniter.h
│       ├── casemap.h
│       ├── char16ptr.h
│       ├── chariter.h
│       ├── choicfmt.h
│       ├── coleitr.h
│       ├── coll.h
│       ├── compactdecimalformat.h
│       ├── curramt.h
│       ├── currpinf.h
│       ├── currunit.h
│       ├── datefmt.h
│       ├── dbbi.h
│       ├── dcfmtsym.h
│       ├── decimfmt.h
│       ├── docmain.h
│       ├── dtfmtsym.h
│       ├── dtintrv.h
│       ├── dtitvfmt.h
│       ├── dtitvinf.h
│       ├── dtptngen.h
│       ├── dtrule.h
│       ├── edits.h
│       ├── enumset.h
│       ├── errorcode.h
│       ├── fieldpos.h
│       ├── filteredbrk.h
│       ├── fmtable.h
│       ├── format.h
│       ├── formattedvalue.h
│       ├── fpositer.h
│       ├── gender.h
│       ├── gregocal.h
│       ├── icudataver.h
│       ├── icuplug.h
│       ├── idna.h
│       ├── listformatter.h
│       ├── localebuilder.h
│       ├── localematcher.h
│       ├── localpointer.h
│       ├── locdspnm.h
│       ├── locid.h
│       ├── measfmt.h
│       ├── measunit.h
│       ├── measure.h
│       ├── messagepattern.h
│       ├── msgfmt.h
│       ├── normalizer2.h
│       ├── normlzr.h
│       ├── nounit.h
│       ├── numberformatter.h
│       ├── numberrangeformatter.h
│       ├── numfmt.h
│       ├── numsys.h
│       ├── parseerr.h
│       ├── parsepos.h
│       ├── platform.h
│       ├── plurfmt.h
│       ├── plurrule.h
│       ├── ptypes.h
│       ├── putil.h
│       ├── rbbi.h
│       ├── rbnf.h
│       ├── rbtz.h
│       ├── regex.h
│       ├── region.h
│       ├── reldatefmt.h
│       ├── rep.h
│       ├── resbund.h
│       ├── schriter.h
│       ├── scientificnumberformatter.h
│       ├── search.h
│       ├── selfmt.h
│       ├── simpleformatter.h
│       ├── simpletz.h
│       ├── smpdtfmt.h
│       ├── sortkey.h
│       ├── std_string.h
│       ├── strenum.h
│       ├── stringoptions.h
│       ├── stringpiece.h
│       ├── stringtriebuilder.h
│       ├── stsearch.h
│       ├── symtable.h
│       ├── tblcoll.h
│       ├── timezone.h
│       ├── tmunit.h
│       ├── tmutamt.h
│       ├── tmutfmt.h
│       ├── translit.h
│       ├── tzfmt.h
│       ├── tznames.h
│       ├── tzrule.h
│       ├── tztrans.h
│       ├── ubidi.h
│       ├── ubiditransform.h
│       ├── ubrk.h
│       ├── ucal.h
│       ├── ucasemap.h
│       ├── ucat.h
│       ├── uchar.h
│       ├── ucharstriebuilder.h
│       ├── ucharstrie.h
│       ├── uchriter.h
│       ├── uclean.h
│       ├── ucnv_cb.h
│       ├── ucnv_err.h
│       ├── ucnv.h
│       ├── ucnvsel.h
│       ├── ucoleitr.h
│       ├── ucol.h
│       ├── uconfig.h
│       ├── ucpmap.h
│       ├── ucptrie.h
│       ├── ucsdet.h
│       ├── ucurr.h
│       ├── udata.h
│       ├── udateintervalformat.h
│       ├── udat.h
│       ├── udatpg.h
│       ├── udisplaycontext.h
│       ├── uenum.h
│       ├── ufieldpositer.h
│       ├── uformattable.h
│       ├── uformattedvalue.h
│       ├── ugender.h
│       ├── uidna.h
│       ├── uiter.h
│       ├── uldnames.h
│       ├── ulistformatter.h
│       ├── ulocdata.h
│       ├── uloc.h
│       ├── umachine.h
│       ├── umisc.h
│       ├── umsg.h
│       ├── umutablecptrie.h
│       ├── unifilt.h
│       ├── unifunct.h
│       ├── unimatch.h
│       ├── unirepl.h
│       ├── uniset.h
│       ├── unistr.h
│       ├── unorm2.h
│       ├── unorm.h
│       ├── unumberformatter.h
│       ├── unum.h
│       ├── unumsys.h
│       ├── uobject.h
│       ├── upluralrules.h
│       ├── uregex.h
│       ├── uregion.h
│       ├── ureldatefmt.h
│       ├── urename.h
│       ├── urep.h
│       ├── ures.h
│       ├── uscript.h
│       ├── usearch.h
│       ├── uset.h
│       ├── usetiter.h
│       ├── ushape.h
│       ├── uspoof.h
│       ├── usprep.h
│       ├── ustdio.h
│       ├── ustream.h
│       ├── ustring.h
│       ├── ustringtrie.h
│       ├── utext.h
│       ├── utf16.h
│       ├── utf32.h
│       ├── utf8.h
│       ├── utf.h
│       ├── utf_old.h
│       ├── utmscale.h
│       ├── utrace.h
│       ├── utrans.h
│       ├── utypes.h
│       ├── uvernum.h
│       ├── uversion.h
│       └── vtzone.h
├── lib
│   ├── icu
│   │   ├── 67.1
│   │   │   ├── Makefile.inc
│   │   │   └── pkgdata.inc
│   │   ├── current -> 67.1
│   │   ├── Makefile.inc -> current/Makefile.inc
│   │   └── pkgdata.inc -> current/pkgdata.inc
│   ├── libicudata.67.1.dylib
│   ├── libicudata.67.dylib -> libicudata.67.1.dylib
│   ├── libicudata.dylib -> libicudata.67.1.dylib
│   ├── libicui18n.67.1.dylib
│   ├── libicui18n.67.dylib -> libicui18n.67.1.dylib
│   ├── libicui18n.dylib -> libicui18n.67.1.dylib
│   ├── libicuio.67.1.dylib
│   ├── libicuio.67.dylib -> libicuio.67.1.dylib
│   ├── libicuio.dylib -> libicuio.67.1.dylib
│   ├── libicutest.67.1.dylib
│   ├── libicutest.67.dylib -> libicutest.67.1.dylib
│   ├── libicutest.dylib -> libicutest.67.1.dylib
│   ├── libicutu.67.1.dylib
│   ├── libicutu.67.dylib -> libicutu.67.1.dylib
│   ├── libicutu.dylib -> libicutu.67.1.dylib
│   ├── libicuuc.67.1.dylib
│   ├── libicuuc.67.dylib -> libicuuc.67.1.dylib
│   ├── libicuuc.dylib -> libicuuc.67.1.dylib
│   └── pkgconfig
│       ├── icu-i18n.pc
│       ├── icu-io.pc
│       └── icu-uc.pc
├── logs
│   ├── fix_identity_mismatch_libicudata.67.1.dylib.log.gz
│   ├── fix_identity_mismatch_libicui18n.67.1.dylib.log.gz
│   ├── fix_identity_mismatch_libicuio.67.1.dylib.log.gz
│   ├── fix_identity_mismatch_libicutest.67.1.dylib.log.gz
│   ├── fix_identity_mismatch_libicutu.67.1.dylib.log.gz
│   ├── fix_identity_mismatch_libicuuc.67.1.dylib.log.gz
│   ├── ICU.log.gz
│   ├── update_linkage_derb_libicudata.67.dylib.log.gz
│   ├── update_linkage_derb_libicui18n.67.dylib.log.gz
│   ├── update_linkage_derb_libicuio.67.dylib.log.gz
│   ├── update_linkage_derb_libicutu.67.dylib.log.gz
│   ├── update_linkage_derb_libicuuc.67.dylib.log.gz
│   ├── update_linkage_genbrk_libicudata.67.dylib.log.gz
│   ├── update_linkage_genbrk_libicui18n.67.dylib.log.gz
│   ├── update_linkage_genbrk_libicutu.67.dylib.log.gz
│   ├── update_linkage_genbrk_libicuuc.67.dylib.log.gz
│   ├── update_linkage_genccode_libicudata.67.dylib.log.gz
│   ├── update_linkage_genccode_libicui18n.67.dylib.log.gz
│   ├── update_linkage_genccode_libicutu.67.dylib.log.gz
│   ├── update_linkage_genccode_libicuuc.67.dylib.log.gz
│   ├── update_linkage_gencfu_libicudata.67.dylib.log.gz
│   ├── update_linkage_gencfu_libicui18n.67.dylib.log.gz
│   ├── update_linkage_gencfu_libicutu.67.dylib.log.gz
│   ├── update_linkage_gencfu_libicuuc.67.dylib.log.gz
│   ├── update_linkage_gencmn_libicudata.67.dylib.log.gz
│   ├── update_linkage_gencmn_libicui18n.67.dylib.log.gz
│   ├── update_linkage_gencmn_libicutu.67.dylib.log.gz
│   ├── update_linkage_gencmn_libicuuc.67.dylib.log.gz
│   ├── update_linkage_gencnval_libicudata.67.dylib.log.gz
│   ├── update_linkage_gencnval_libicui18n.67.dylib.log.gz
│   ├── update_linkage_gencnval_libicutu.67.dylib.log.gz
│   ├── update_linkage_gencnval_libicuuc.67.dylib.log.gz
│   ├── update_linkage_gendict_libicudata.67.dylib.log.gz
│   ├── update_linkage_gendict_libicui18n.67.dylib.log.gz
│   ├── update_linkage_gendict_libicutu.67.dylib.log.gz
│   ├── update_linkage_gendict_libicuuc.67.dylib.log.gz
│   ├── update_linkage_gennorm2_libicudata.67.dylib.log.gz
│   ├── update_linkage_gennorm2_libicui18n.67.dylib.log.gz
│   ├── update_linkage_gennorm2_libicutu.67.dylib.log.gz
│   ├── update_linkage_gennorm2_libicuuc.67.dylib.log.gz
│   ├── update_linkage_genrb_libicudata.67.dylib.log.gz
│   ├── update_linkage_genrb_libicui18n.67.dylib.log.gz
│   ├── update_linkage_genrb_libicutu.67.dylib.log.gz
│   ├── update_linkage_genrb_libicuuc.67.dylib.log.gz
│   ├── update_linkage_gensprep_libicudata.67.dylib.log.gz
│   ├── update_linkage_gensprep_libicui18n.67.dylib.log.gz
│   ├── update_linkage_gensprep_libicutu.67.dylib.log.gz
│   ├── update_linkage_gensprep_libicuuc.67.dylib.log.gz
│   ├── update_linkage_icuinfo_libicudata.67.dylib.log.gz
│   ├── update_linkage_icuinfo_libicui18n.67.dylib.log.gz
│   ├── update_linkage_icuinfo_libicutu.67.dylib.log.gz
│   ├── update_linkage_icuinfo_libicuuc.67.dylib.log.gz
│   ├── update_linkage_icupkg_libicudata.67.dylib.log.gz
│   ├── update_linkage_icupkg_libicui18n.67.dylib.log.gz
│   ├── update_linkage_icupkg_libicutu.67.dylib.log.gz
│   ├── update_linkage_icupkg_libicuuc.67.dylib.log.gz
│   ├── update_linkage_libicui18n.67.1.dylib_libicudata.67.dylib.log.gz
│   ├── update_linkage_libicui18n.67.1.dylib_libicuuc.67.dylib.log.gz
│   ├── update_linkage_libicuio.67.1.dylib_libicudata.67.dylib.log.gz
│   ├── update_linkage_libicuio.67.1.dylib_libicui18n.67.dylib.log.gz
│   ├── update_linkage_libicuio.67.1.dylib_libicuuc.67.dylib.log.gz
│   ├── update_linkage_libicutest.67.1.dylib_libicudata.67.dylib.log.gz
│   ├── update_linkage_libicutest.67.1.dylib_libicui18n.67.dylib.log.gz
│   ├── update_linkage_libicutest.67.1.dylib_libicutu.67.dylib.log.gz
│   ├── update_linkage_libicutest.67.1.dylib_libicuuc.67.dylib.log.gz
│   ├── update_linkage_libicutu.67.1.dylib_libicudata.67.dylib.log.gz
│   ├── update_linkage_libicutu.67.1.dylib_libicui18n.67.dylib.log.gz
│   ├── update_linkage_libicutu.67.1.dylib_libicuuc.67.dylib.log.gz
│   ├── update_linkage_libicuuc.67.1.dylib_libicudata.67.dylib.log.gz
│   ├── update_linkage_makeconv_libicudata.67.dylib.log.gz
│   ├── update_linkage_makeconv_libicui18n.67.dylib.log.gz
│   ├── update_linkage_makeconv_libicutu.67.dylib.log.gz
│   ├── update_linkage_makeconv_libicuuc.67.dylib.log.gz
│   ├── update_linkage_pkgdata_libicudata.67.dylib.log.gz
│   ├── update_linkage_pkgdata_libicui18n.67.dylib.log.gz
│   ├── update_linkage_pkgdata_libicutu.67.dylib.log.gz
│   ├── update_linkage_pkgdata_libicuuc.67.dylib.log.gz
│   ├── update_linkage_uconv_libicudata.67.dylib.log.gz
│   ├── update_linkage_uconv_libicui18n.67.dylib.log.gz
│   ├── update_linkage_uconv_libicuuc.67.dylib.log.gz
│   ├── update_rpath_derb_libicuio.67.dylib.log.gz
│   ├── update_rpath_genbrk_libicutu.67.dylib.log.gz
│   ├── update_rpath_genccode_libicutu.67.dylib.log.gz
│   ├── update_rpath_gencfu_libicutu.67.dylib.log.gz
│   ├── update_rpath_gencmn_libicutu.67.dylib.log.gz
│   ├── update_rpath_gencnval_libicutu.67.dylib.log.gz
│   ├── update_rpath_gendict_libicutu.67.dylib.log.gz
│   ├── update_rpath_gennorm2_libicutu.67.dylib.log.gz
│   ├── update_rpath_genrb_libicutu.67.dylib.log.gz
│   ├── update_rpath_gensprep_libicutu.67.dylib.log.gz
│   ├── update_rpath_icuinfo_libicutu.67.dylib.log.gz
│   ├── update_rpath_icupkg_libicutu.67.dylib.log.gz
│   ├── update_rpath_libicui18n.67.1.dylib_libicudata.67.dylib.log.gz
│   ├── update_rpath_libicuio.67.1.dylib_libicui18n.67.dylib.log.gz
│   ├── update_rpath_libicutest.67.1.dylib_libicutu.67.dylib.log.gz
│   ├── update_rpath_libicutu.67.1.dylib_libicui18n.67.dylib.log.gz
│   ├── update_rpath_libicuuc.67.1.dylib_libicudata.67.dylib.log.gz
│   ├── update_rpath_makeconv_libicutu.67.dylib.log.gz
│   ├── update_rpath_pkgdata_libicutu.67.dylib.log.gz
│   └── update_rpath_uconv_libicui18n.67.dylib.log.gz
├── sbin
│   ├── escapesrc
│   ├── genccode
│   ├── gencmn
│   ├── gennorm2
│   ├── gensprep
│   └── icupkg
└── share
    ├── icu
    │   └── 67.1
    │       ├── config
    │       │   └── mh-darwin
    │       ├── install-sh
    │       ├── LICENSE
    │       └── mkinstalldirs
    ├── licenses
    │   └── ICU
    │       └── LICENSE
    └── man
        ├── man1
        │   ├── derb.1
        │   ├── genbrk.1
        │   ├── gencfu.1
        │   ├── gencnval.1
        │   ├── gendict.1
        │   ├── genrb.1
        │   ├── icu-config.1
        │   ├── makeconv.1
        │   ├── pkgdata.1
        │   └── uconv.1
        └── man8
            ├── genccode.8
            ├── gencmn.8
            ├── gensprep.8
            └── icupkg.8
```
`libicudata.67.dylib` (and `libicudata.67.1.dylib`) should be in the `lib/` directory.  The `NOT FOUND` label you showed before is probably misleading

**Comment by bulbulahmmed** [comment]
Here is the command output. I ran it after this command 
    import Cairo
It showed LoadError. Next, I tried the following command. 

    using DependencyWalker
    Library("/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/libicudata.67.dylib")
    ✗ /Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/libicudata.67.dylib (NOT FOUND)

I totally get your point. There should be a data structure but it is not there.

**Comment by giordano** [comment]
Can you please show the content of the directory `/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/lib/`?

**Comment by bulbulahmmed** [comment]
lib has a directory called icu
icu has another directory called 67.1
67.1 has makefile.inc and include.inc files.

<img width="728" alt="Screen Shot 2020-10-31 at 12 45 03 PM" src="https://user-images.githubusercontent.com/37277355/97787360-363da580-1b77-11eb-9c65-529ebaee88dd.png">

**Comment by giordano** [comment]
Well, that's totally wrong (and the `NOT FOUND` label was accurate), no idea how that could happen.  Delete the entire directory `/Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598/`, restart Julia and try to load `Cairo` again, that should be redownloaded automatically.

**Comment by bulbulahmmed** [comment]
Thanks. Awesome! Now, I cannot delete that directory. It says directory is not empty or permission denied and both of them should not come.

**Comment by bulbulahmmed** [comment]
Also, I uninstalled Cairo then reinstalled. But, it is showing the same error.

**Comment by giordano** [comment]
> Thanks. Awesome! Now, I cannot delete that directory. It says directory is not empty or permission denied and both of them should not come.

Right, unfortunately ICU has weird permissions and we can't do much about that.  You need to do something like

```
chmod u+w -R /Users/bulbulahmmed/.julia/artifacts/cecc5d9174d113ce6a5a35798d26f54375402598
```

to give your user write permissions, before deleting some files.

> Also, I uninstalled Cairo then reinstalled. But, it is showing the same error.

Yes, that won't help anything.

**Comment by bulbulahmmed** [comment]
Hi Giordano,

It worked. I appreciate your help. I had to use 

    chmod -R 777 . 

in the cecc5d9174d113ce6a5a35798d26f54375402598. Then I could delete it. Next, I started Julia fresh and imported Cairo successfully.

**Comment by giordano** [comment]
Just to understand: have you installed Cairo.jl before? Have you ever run the `]gc` command?

**Comment by bulbulahmmed** [comment]
I installed Cairo before. Was that an issue? No, I never ran ]gc. Just I did.

**Comment by giordano** [comment]
> I installed Cairo before. Was that an issue?

Not sure, I don't think so.  Especially if you've never run `]gc`.
