### ISSUE TITLE
Support for cairo_image_surface_get_data?

### ISSUE THREAD

**Issue by luchr** [JuliaGraphics/Cairo.jl#342]
Hello Cairo-team,

I cannot find a way to directly access the data of an image surface (which is done via [cairo_image_surface_get_data](https://www.cairographics.org/manual/cairo-Image-Surfaces.html#cairo-image-surface-get-data) in Cairo). Is this somewhere hidden in Cairo.jl?

Otherwise. Here is my workaround/implementation:

```julia
function image_surface_get_data(surface::CairoSurface{T}) where {T}
    Cairo.flush(surface)
    return ccall(
        (:cairo_image_surface_get_data, Cairo.libcairo),
        Ptr{T},
        (Ptr{Nothing},),
        surface.ptr)
end
```

**Comment by lobingera** [comment]
a) Put a PR
b) In https://github.com/JuliaGraphics/Cairo.jl/blob/master/test/runtests.jl#L120-L127 you can see how to setup an Image Surface with external data and read from it.

**Comment by luchr** [comment]
Thank you.
