### ISSUE TITLE
Support for newer upstream Cairo versions (>=1.17.2)?

### ISSUE THREAD

**Issue by JeffreyPalmer** [JuliaGraphics/Cairo.jl#354]
Hi!

I don't have a bug but rather have a question: Is there anything preventing upgrading to the most-recent versions of Cairo? Specifically, I'm interested in versions after [1.17.2](https://www.cairographics.org/news/cairo-1.17.2/), as that version introduced support for the RGBA128F image format, which I'd love to support for my work. 

I'm happy to implement this support, but I just wanted to check in to see if there were any potential issues I should be aware of before starting down that path.

Thanks!

**Comment by lobingera** [comment]
Major part of work will be in the build scripts for BinaryBuilder https://docs.binarybuilder.org/stable/ see e.g. https://github.com/JuliaPackaging/Yggdrasil/blob/master/C/Cairo/build_tarballs.jl and the dependencies for that - and the dependencies of the dependencies etc.

But just for my curiosity: do you know any examples of SW using actually RGBA128F ?

**Comment by giordano** [comment]
That's a development version though, right?  I seem to remember Cairo uses the scheme `X.<even number>` for stable releases, and `X.<odd number>` for snapshots.  For example also Debian is still stuck to 1.16.0, and the latest version available at https://www.cairographics.org/releases/ is 1.16.0.

**Comment by lobingera** [comment]
it's called snapshot, not release. But 1.17.4 is already there and has moved to meson build system. So supporting this is anyway an investment.
