### ISSUE TITLE
Memory allocation errors for line_to()

### ISSUE THREAD

**Issue by sswatson** [JuliaGraphics/Cairo.jl#98]
I'm getting memory allocation problems when extensively using line_to(). The code below runs fine with 10,000 rectangle()'s, but when I draw rectangles with move_to() and line_to() (commented out below) it inevitably crashes the kernel (in IJulia) or gives a memory allocation error. I'm using v0.3.6. 

```julia
using Cairo
c = CairoRGBSurface(256,256)
cr = CairoContext(c) 

set_source_rgb(cr,1.0,1.0,1.0) 
paint(cr)

set_source_rgb(cr, 0, 0, 0)
set_line_width(cr,1.0)

for k=1:10_000
    x,y = 256*rand(),256*rand()
#    move_to(cr,x,y)
#    line_to(cr,x+10.0,y+10.0)
#    line_to(cr,x,y+20.0)
#    line_to(cr,x-10.0,y+10.0)
#    line_to(cr,x,y)
#    close_path(cr)
    rectangle (cr, 256*rand(), 256*rand(), 10.0, 10.0)
    stroke(cr)
end

write_to_png(c,"boxes.png")
```

**Comment by lobingera** [comment]
can you give some more context? (like a copy of the error messages)

I just tried with a fresh install of ijulia and on the REPL and succeed in both methods. I'm wondering if you maybe not call Cairo.rectangle but something else on the way.

**Comment by sswatson** [comment]
Sorry--I should have been more clear. The version that breaks is the one with the commented out commands. If I open a fresh install of Julia 0.3.6 on my Mac, add the Cairo package, and then run the this block of code, then I get the error printed below the code. 

```julia
using Cairo
c = CairoRGBSurface(256,256)
cr = CairoContext(c) 

set_source_rgb(cr,1.0,1.0,1.0) 
paint(cr)

set_source_rgb(cr, 0, 0, 0)
set_line_width(cr,1.0)

for k=1:10_000
    x,y = 256*rand(),256*rand()
    move_to(cr,x,y)
    line_to(cr,x+10.0,y+10.0)
    line_to(cr,x,y+20.0)
    line_to(cr,x-10.0,y+10.0)
    line_to(cr,x,y)
    close_path(cr)
    stroke(cr)
end

write_to_png(c,"boxes.png")
```

```
ERROR: MemoryError()
 in stroke at /Users/sswatson/.julia/v0.3/Cairo/src/Cairo.jl:390
 in anonymous at no file:10
```

I don't know whether this is helpful at all, but if I run the same block a second time, then I get a seg fault. 

```
signal (11): Segmentation fault: 11
_fill_xrgb32_lerp_opaque_spans at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
_cairo_tor_scan_converter_generate at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
composite_polygon at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
clip_and_composite_polygon at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
_cairo_spans_compositor_stroke at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
_cairo_compositor_stroke at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
_cairo_image_surface_stroke at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
_cairo_surface_stroke at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
_cairo_gstate_stroke at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
_cairo_default_context_stroke at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
cairo_stroke at /Users/sswatson/.julia/v0.3/Homebrew/deps/usr/lib/libcairo.2.dylib (unknown line)
stroke at /Users/sswatson/.julia/v0.3/Cairo/src/Cairo.jl:390
jlcall_stroke_20290 at  (unknown line)
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/./julia.h:982
anonymous at no file:9
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/./julia.h:982
jl_f_top_eval at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/builtins.c:399
eval_user_input at REPL.jl:53
jlcall_eval_user_input_19895 at  (unknown line)
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/./julia.h:982
anonymous at task.jl:95
jl_apply at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/task.c:423
julia_trampoline at /Users/vagrant/buildbot/slave/package_osx10_9/build/src/init.c:1032
```

**Comment by lobingera** [comment]
So the memory problem is actually happening within your libcairo and not the interface between cairo and julia. I'm not a master of Homebrew, but can you rebuilt your libcairo? There is/should be local testing of cairo.

**Comment by lobingera** [comment]
This takes an interesting turn: http://lists.cairographics.org/archives/cairo/2015-March/026019.html also mentiones a crash in the same part of cairo.

**Comment by sswatson** [comment]
Thanks for tracking that down. The thread is just two days old; I wonder whether this problem was introduced recently. I've noticed that I only have an issue when the figure I'm drawing is closed or almost closed (regardless of whether close_path is called). Without really understanding Ilya's description, I think that might be consistent with what he described. 

To try a different system, I ran Pkg.update() in JuliaBox and the code above did not have problems. On my own machine, I moved aside my package folder and reinstalled everything from scratch, and the problem persists.

**Comment by lobingera** [comment]
I'm not part of the cairo development, so i might be wrong here, but the closest thing in bug reportin seems to be https://bugs.freedesktop.org/show_bug.cgi?id=85372 and that is showing up on 1.14.0, but not on previous versions and not on the 1.14.2. release candidate. Cairo.jl is (afaik) only using < 1.10 features (that's why i have a pull request for 1.12 features) so you can use any version pre 1.14.

**Comment by sswatson** [comment]
Downgrading from 1.14 to 1.12 solved the problem. Thanks!
